Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2021-03, with the labels that each got.

#583 [1048] Disable browser auto-fill
  .browserslistrc
  app/helpers/application_helper.rb
  app/views/system_admin/providers/new.html.erb
  app/views/system_admin/users/new.html.erb
  app/views/trainees/contact_details/edit.html.erb
  app/views/trainees/degrees/_non_uk_degree_form.html.erb
  app/views/trainees/diversity/disability_details/edit.html.erb
  app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
  app/views/trainees/personal_details/edit.html.erb
  app/views/trainees/trainee_ids/edit.html.erb
  app/views/trainees/training_details/edit.html.erb
  app/views/trainees/withdrawals/show.html.erb
  app/webpacker/packs/application.js
  app/webpacker/scripts/global/disable-browser-autofill.js
Labels: DO NOT MERGE

#633 1139 create an environment for accessibility audit
  Gemfile
  Makefile
  config/environments/audit.rb
  config/settings/audit.yml
  terraform/workspace-variables/app_config.yml
  terraform/workspace-variables/audit.sh
  terraform/workspace-variables/audit.tfvars
  terraform/workspace-variables/audit_backend.tfvars
  terraform/workspace-variables/pen.tfvars
  terraform/workspace-variables/review.sh
Labels: DevOps

#666 Reduce docker image size
  .github/workflows/build.yml
  Dockerfile
Labels: DevOps

#701 Bump mimemagic to 0.3.9
  Dockerfile
  Gemfile.lock
Labels: DevOps, dependencies
