Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2021-07, with the labels that each got.

#1097 Wait for the review app deployment to finish in PR build workflow
  .github/workflows/build.yml
Labels: DevOps

#1115 Deploy review app only if labelled
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
Labels: DevOps, deploy

#1109 [2173] Use min_alpha in ensure alphanumeric course codes
  spec/controllers/trainees/subject_specialisms_controller_spec.rb
  spec/factories/courses.rb
  spec/factories/subjects.rb
Labels: deploy

#1113 [2111] Subjects show matching specialism first
  app/lib/dttp/code_sets/allocation_subjects.rb
Labels: deploy

#1110 [2159] schools snagging nonjs form
  app/views/trainees/employing_schools/_results.html.erb
  app/views/trainees/lead_schools/_results.html.erb
  config/locales/en.yml
  spec/support/shared_examples/school_form_validations.rb
Labels: deploy

#1122 Use make commands in ci workflow
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .gitignore
  Makefile
  terraform/terraform.tf
  terraform/variables.tf
Labels: DevOps, deploy

#1108 [2158] Schools snagging JS and Non-JS school form
  app/controllers/trainees/employing_schools_controller.rb
  app/controllers/trainees/lead_schools_controller.rb
  app/forms/schools/employing_school_form.rb
  app/forms/schools/form.rb
  app/forms/schools/lead_school_form.rb
  app/views/trainees/employing_schools/_results.html.erb
  app/views/trainees/lead_schools/_no_results.html.erb
  app/views/trainees/lead_schools/_results.html.erb
  app/views/trainees/lead_schools/edit.html.erb
  config/initializers/publish_subject_mapping.rb
  config/locales/en.yml
  spec/support/shared_examples/school_form_validations.rb
Labels: deploy

#1106 [2150] Fix check details inset text spacing
  app/components/collapsed_section/style.scss
  app/views/trainees/check_details/show.html.erb
Labels: deploy

#1127 Add apply drafts to example data script
  lib/tasks/example_data.rake
Labels: deploy

#1101 [2103] bursaries new tiered bursary form
  app/components/funding/view.rb
  app/controllers/trainees/funding/bursaries_controller.rb
  app/controllers/trainees/funding/training_initiatives_controller.rb
  app/forms/funding/bursary_form.rb
  app/lib/route_data_manager.rb
  app/models/trainee.rb
  app/services/calculate_bursary.rb
  app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
  app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
  app/views/trainees/funding/bursaries/edit.html.erb
  config/locales/en.yml
  spec/components/funding/view_spec.rb
  spec/factories/trainees.rb
  spec/features/form_sections/teacher_training_data/edit_bursary_spec.rb
  spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
  spec/forms/funding/bursary_form_spec.rb
  spec/lib/route_data_manager_spec.rb
  spec/models/trainee_spec.rb
  spec/services/calculate_bursary_spec.rb
  spec/support/page_objects/trainees/funding/bursary.rb
Labels: deploy

#1123 [2206] Remove pen and rollover configuration
  config/environments/pen.rb
  config/environments/rollover.rb
  config/settings/pen.yml
  config/settings/rollover.yml
  terraform/workspace-variables/app_config.yml
  terraform/workspace-variables/pen.sh
  terraform/workspace-variables/pen.tfvars
  terraform/workspace-variables/pen_backend.tfvars
  terraform/workspace-variables/rollover.sh
  terraform/workspace-variables/rollover.tfvars
  terraform/workspace-variables/rollover_backend.tfvars
Labels: DevOps

#1116 Upgrade to Ruby 2.7.4
  .github/workflows/smoke-test.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: DevOps

#1145 [2180] Course level filter
  app/components/filters/view.html.erb
  app/controllers/trainees_controller.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/views/trainees/index.html.erb
  config/initializers/course_levels.rb
  config/locales/en.yml
  spec/factories/trainees.rb
  spec/features/trainee_actions/filtering_trainees_spec.rb
  spec/services/trainees/filter_spec.rb
  spec/support/page_objects/trainees/index.rb
Labels: deploy

#1153 Workflow to backup prod DB in Azure storage
  .github/workflows/database-backup.yml
Labels: DevOps

#1112 [2105 + 2104] make publish course details flow work
  app/components/confirm_publish_course/view.html.erb
  app/components/confirm_publish_course/view.rb
  app/controllers/trainees/confirm_publish_course_controller.rb
  app/controllers/trainees/language_specialisms_controller.rb
  app/controllers/trainees/publish_course_details_controller.rb
  app/controllers/trainees/subject_specialisms_controller.rb
  app/forms/confirm_publish_course_form.rb
  app/forms/language_specialisms_form.rb
  app/forms/publish_course_details_form.rb
  app/forms/subject_specialism_form.rb
  app/helpers/course_details_helper.rb
  app/lib/dttp/code_sets/allocation_subjects.rb
  app/services/calculate_subject_specialism_type.rb
  app/services/calculate_subject_specialisms.rb
  app/views/trainees/confirm_publish_course/edit.html.erb
  app/views/trainees/language_specialisms/edit.html.erb
  app/views/trainees/subject_specialisms/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/confirm_publish_course/view_preview.rb
  spec/components/confirm_publish_course/view_spec.rb
  spec/controllers/trainees/subject_specialisms_controller_spec.rb
  spec/factories/courses.rb
  spec/factories/trainees.rb
  spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
  spec/forms/confirm_publish_course_form_spec.rb
  spec/forms/language_specialisms_form_spec.rb
  spec/forms/subject_specialism_form_spec.rb
  spec/support/features/course_details_steps.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/trainees/confirm_publish_course.rb
  spec/support/page_objects/trainees/language_specialism.rb
  spec/support/page_objects/trainees/subject_specialism.rb
Labels: deploy

#1151 [1982] Client side autocomplete - handling punctuation
  app/components/form_components/autocomplete/sort.js
  app/webpacker/scripts/autocomplete_sort.spec.js
Labels: deploy

#1126 [2181] Update trainee start date question
  app/controllers/trainees/training_details_controller.rb
  app/forms/training_details_form.rb
  app/views/trainees/start_dates/edit.html.erb
  app/views/trainees/training_details/edit.html.erb
  config/locales/en.yml
  spec/features/form_sections/teacher_training_data/edit_training_details_spec.rb
  spec/forms/training_details_form_spec.rb
  spec/support/features/training_details_steps.rb
  spec/support/page_objects/trainees/training_details.rb
  spec/support/shared_examples/rendering_the_funding_section.rb
Labels: deploy

#1143 [2262] Change link and link text for early years bursary
  app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
  app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
  config/locales/en.yml
Labels: deploy

#1139 [2210] Suppress confirmation page when editing apply draft sections
  app/controllers/trainees/contact_details_controller.rb
  app/controllers/trainees/course_details_controller.rb
  app/controllers/trainees/degrees_controller.rb
  app/controllers/trainees/diversity/disclosures_controller.rb
  app/controllers/trainees/personal_details_controller.rb
  app/controllers/trainees/training_details_controller.rb
  spec/controllers/trainees/personal_details_controller_spec.rb
  spec/controllers/trainees/training_details_controller_spec.rb
Labels: deploy

#1136 [2231] Add pgta route
  app/helpers/task_list_helper.rb
  app/lib/training_route_manager.rb
  config/initializers/training_routes.rb
  config/locales/en.yml
  config/settings.yml
  config/settings/development.yml
  config/settings/qa.yml
  config/settings/review.yml
  config/settings/staging.yml
  spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb
  spec/models/trainee_spec.rb
  spec/services/dttp/contact_update_spec.rb
  spec/services/dttp/register_for_trn_spec.rb
  spec/support/features/training_route_steps.rb
  spec/support/page_objects/trainees/new.rb
Labels: deploy

#1114 [2116] Make `Trainee#sha` less sensitive
  app/models/trainee.rb
  db/data/20210719132235_reset_update_sha.rb
  spec/models/trainee_spec.rb
Labels: deploy

#1134 [2213] Handle degree deletion on apply draft page
  app/components/sections/view.rb
  app/controllers/trainees/degrees_controller.rb
  app/forms/apply_trainee_data_form.rb
  config/locales/en.yml
  spec/components/apply_trainee_data/view_spec.rb
Labels: deploy

#1132 [2212] update filter toggle to be able to filter on apply drafts
  app/controllers/trainees_controller.rb
  app/models/trainee.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/views/trainees/index.html.erb
  config/locales/en.yml
  config/settings.yml
  config/settings/development.yml
  config/settings/qa.yml
  config/settings/review.yml
  spec/features/trainee_actions/filtering_trainees_spec.rb
  spec/models/trainee_filter_spec.rb
  spec/models/trainee_spec.rb
  spec/services/trainees/filter_spec.rb
  spec/support/page_objects/trainees/index.rb
Labels: deploy

#1155 [2273] Add ability to search for allocation subject in filter
  app/controllers/trainees_controller.rb
  app/helpers/course_details_helper.rb
  app/models/trainee.rb
  app/services/trainees/filter.rb
  db/schema.rb
  lib/tasks/example_data.rake
  spec/factories/trainees.rb
  spec/models/trainee_spec.rb
Labels: deploy

#1161 [2272] Bursary row for non-draft trainees
  app/components/funding/view.rb
  config/locales/en.yml
  spec/components/funding/view_spec.rb
Labels: deploy

#1146 [2211] Apply draft sections use "Reviewed" text instead of confirm
  app/helpers/confirm_details_helper.rb
  app/views/trainees/confirm_details/_form.html.erb
  config/locales/en.yml
Labels: deploy

#1152 [2215] Check details page needs to show collapsed version of apply draft sections
  app/components/sections/view.rb
  app/controllers/trainees/apply_trainee_data_controller.rb
  app/forms/apply_trainee_data_form.rb
  app/forms/trn_submission_form.rb
  app/helpers/task_list_helper.rb
  app/models/progress.rb
  app/views/trainees/check_details/_apply_draft_trainee_check_details.html.erb
  app/views/trainees/check_details/_draft_trainee_check_details.html.erb
  app/views/trainees/check_details/show.html.erb
  config/locales/en.yml
  spec/components/apply_trainee_data/view_preview.rb
  spec/components/apply_trainee_data/view_spec.rb
  spec/features/trainee_actions/submit_for_trn_spec.rb
  spec/forms/apply_trainees/apply_trainee_data_form_spec.rb
Labels: deploy

#1156 [2209] Apply draft course details section
  app/components/apply_applications/confirm_course/view.html.erb
  app/components/apply_applications/confirm_course/view.rb
  app/components/apply_applications/trainee_data/view.html.erb
  app/components/apply_applications/trainee_data/view.rb
  app/components/apply_trainee_data/view.rb
  app/components/sections/view.rb
  app/controllers/trainees/apply_applications/confirm_courses_controller.rb
  app/controllers/trainees/apply_applications/course_details_controller.rb
  app/controllers/trainees/apply_applications/trainee_data_controller.rb
  app/controllers/trainees/apply_trainee_data_controller.rb
  app/controllers/trainees/degrees_controller.rb
  app/controllers/trainees/language_specialisms_controller.rb
  app/controllers/trainees/publish_course_details_controller.rb
  app/controllers/trainees/subject_specialisms_controller.rb
  app/forms/apply_applications/confirm_course_form.rb
  app/forms/apply_applications/trainee_data_form.rb
  app/forms/apply_trainee_data_form.rb
  app/forms/confirm_publish_course_form.rb
  app/forms/language_specialisms_form.rb
  app/forms/subject_specialism_form.rb
  app/forms/trn_submission_form.rb
  app/helpers/task_list_helper.rb
  app/models/trainee.rb
  app/services/trainees/create_from_apply.rb
  app/views/trainees/apply_applications/confirm_courses/show.html.erb
  app/views/trainees/apply_applications/course_details/show.html.erb
  app/views/trainees/apply_applications/trainee_data/edit.html.erb
  app/views/trainees/apply_trainee_data/edit.html.erb
  app/views/trainees/language_specialisms/edit.html.erb
  app/views/trainees/publish_course_details/edit.html.erb
  app/views/trainees/subject_specialisms/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  lib/tasks/example_data.rake
  spec/components/apply_applications/confirm_course/view_preview.rb
  spec/components/apply_applications/confirm_course/view_spec.rb
  spec/components/apply_applications/trainee_data/view_preview.rb
  spec/components/apply_applications/trainee_data/view_spec.rb
  spec/components/apply_trainee_data/view_preview.rb
  spec/components/apply_trainee_data/view_spec.rb
  spec/components/confirm_publish_course/view_spec.rb
  spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
  spec/forms/apply_applications/apply_trainee_data_form_spec.rb
  spec/forms/apply_trainees/apply_trainee_data_form_spec.rb
  spec/services/trainees/create_from_apply_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/trainees/apply_registrations/confirm_course.rb
  spec/support/page_objects/trainees/apply_registrations/course_details.rb
  spec/support/page_objects/trainees/apply_registrations/trainee_data.rb
  spec/support/page_objects/trainees/apply_trainee_data.rb
  spec/support/shared_examples/rendering_course_confirmation.rb
Labels: deploy

#1148 [2265] Added funding inactive section
  app/components/collapsed_section/view.html.erb
  app/components/collapsed_section/view.rb
  app/components/sections/view.rb
  config/locales/en.yml
  spec/components/collapsed_section/view_preview.rb
  spec/components/collapsed_section/view_spec.rb
Labels: deploy

#1172 [2183] Check what data you need content change
  config/locales/pages/guidance/en.yml
Labels: deploy

#1189 [2314] Fix contact update error
  app/services/dttp/contact_update.rb
  spec/services/dttp/contact_update_spec.rb
Labels: deploy

#1179 [2235] Send degree date to DTTP
  app/lib/dttp/params/degree_qualification.rb
  app/lib/dttp/params/placement_assignment.rb
  spec/lib/dttp/params/degree_qualification_spec.rb
  spec/lib/dttp/params/placement_assignment_spec.rb
Labels: deploy

#1190 [2317] Extract error summary partial into a component
  app/components/apply_applications/trainee_data/view.html.erb
  app/components/error_summary/view.html.erb
  app/components/error_summary/view.rb
  app/views/trainees/check_details/show.html.erb
  config/locales/en.yml
  spec/components/error_summary/view_preview.rb
  spec/components/error_summary/view_spec.rb
Labels: deploy

#1175 [2300] Add soft delete for users
  Gemfile
  Gemfile.lock
  app/models/user.rb
  db/migrate/20210722130748_add_discarded_at_to_users.rb
  db/schema.rb
  docs/datadase-diagram.pdf
  spec/models/user_spec.rb
Labels: deploy

#1182 [1981] Add new wordInSynonym rule to the autocomplete sort
  app/components/form_components/autocomplete/sort.js
  app/webpacker/scripts/autocomplete_sort.spec.js
Labels: deploy

#1176 [2290] Adding synonyms to degree datasets
  app/components/form_components/autocomplete/sort.js
  app/helpers/application_helper.rb
  app/helpers/degrees_helper.rb
  app/lib/dttp/code_sets/degree_subjects.rb
  app/lib/dttp/code_sets/degree_types.rb
  app/lib/dttp/code_sets/institutions.rb
  app/views/trainees/degrees/_non_uk_degree_form.html.erb
  app/views/trainees/degrees/_uk_degree_form.html.erb
  app/webpacker/scripts/autocomplete_sort.spec.js
  spec/helpers/degree_helper_spec.rb
Labels: deploy

#1197 [2322] Update check-details page
  app/components/sections/view.rb
  app/views/trainees/check_details/show.html.erb
  spec/support/page_objects/trainees/check_details/show.rb
Labels: deploy

#1177 [2287] Collect ITT start date for PGTA publish courses
  app/components/apply_applications/confirm_course/view.rb
  app/components/confirm_publish_course/view.rb
  app/controllers/concerns/publish_course_next_path.rb
  app/controllers/trainees/apply_applications/confirm_courses_controller.rb
  app/controllers/trainees/confirm_publish_course_controller.rb
  app/controllers/trainees/itt_start_dates_controller.rb
  app/controllers/trainees/language_specialisms_controller.rb
  app/controllers/trainees/publish_course_details_controller.rb
  app/controllers/trainees/subject_specialisms_controller.rb
  app/forms/apply_applications/confirm_course_form.rb
  app/forms/confirm_publish_course_form.rb
  app/forms/itt_start_date_form.rb
  app/lib/training_route_manager.rb
  app/models/trainee.rb
  app/policies/trainee_policy.rb
  app/services/form_store.rb
  app/views/trainees/apply_applications/confirm_courses/show.html.erb
  app/views/trainees/confirm_publish_course/edit.html.erb
  app/views/trainees/itt_start_dates/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/apply_applications/confirm_course/view_preview.rb
  spec/components/confirm_publish_course/view_preview.rb
  spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
  spec/forms/confirm_publish_course_form_spec.rb
  spec/forms/itt_start_date_form_spec.rb
  spec/lib/training_route_manager_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/trainees/edit_itt_start_date.rb
  spec/support/shared_examples/rendering_course_confirmation.rb
Labels: deploy

#1199 Use commit sha of base branch as docker tag for PR builds
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
  Dockerfile
  docker-compose.yml
Labels: DevOps

#1198 [2319] Change the tag 'not started' to 'incomplete'
  app/components/sections/view.rb
  app/components/task_list/view.rb
  app/models/progress.rb
  app/services/progress_service.rb
  config/locales/en.yml
  spec/components/pages/trainees/check_details/view_preview.rb
  spec/components/sections/view_spec.rb
  spec/components/task_list/view_preview.rb
  spec/components/task_list/view_spec.rb
  spec/factories/trainees.rb
  spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
  spec/features/form_sections/personal_and_education_details/diversities/diversity_progress_spec.rb
  spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
  spec/forms/diversities/disability_disclosure_form_spec.rb
  spec/forms/trainee_id_form_spec.rb
  spec/forms/trainee_start_date_form_spec.rb
  spec/services/progress_service_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/shared_examples/rendering_the_funding_section.rb
Labels: deploy

#1196 [2247] Fix in progress task list links
  app/components/sections/view.rb
  app/components/task_list/view.html.erb
  app/components/task_list/view.rb
  app/models/progress.rb
  app/services/progress_service.rb
  config/locales/en.yml
  spec/components/sections/view_spec.rb
  spec/services/progress_service_spec.rb
  spec/support/features/page_helpers.rb
Labels: deploy

#1203 [2320] Update status card layout and css
  app/components/badges/view.html.erb
  app/components/status_card/style.scss
Labels: deploy

#1194 [2321] Use govuk_link_to helper for guidance links
  app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
  app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
  config/locales/en.yml
Labels: deploy

#1205 [2364] Added validation for ITT start date
  app/forms/itt_start_date_form.rb
  config/locales/en.yml
  spec/forms/itt_start_date_form_spec.rb
Labels: deploy

#1206 [2323] Add validation to date forms requiring 4 numbers
  app/forms/personal_details_form.rb
  app/forms/training_details_form.rb
  config/locales/en.yml
  spec/forms/personal_details_form_spec.rb
  spec/forms/training_details_form_spec.rb
Labels: deploy

#1186 [2255] Set quote character to apostrophe for csv generation
  app/services/exports/trainee_search_data.rb
  spec/services/exports/trainee_search_data_spec.rb
Labels: deploy
