Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-08, with the labels that each got.

#2558 [4384] Remove academic cycle method from trainee
  app/components/funding/view.rb
  app/forms/apply_applications/trainee_data_form.rb
  app/forms/course_details_form.rb
  app/forms/publish_course_details_form.rb
  app/helpers/funding_helper.rb
  app/lib/funding_manager.rb
  app/models/trainee.rb
  app/services/trainees/update.rb
  spec/components/funding/view_spec.rb
  spec/components/sections/view_spec.rb
  spec/models/trainee_spec.rb
  spec/services/exports/trainee_search_data_spec.rb
  spec/support/shared_examples/rendering_the_funding_section.rb
Labels: deploy

#2578 [4397] Update course years form
  app/forms/course_years_form.rb
  spec/features/trainee_actions/change_course_spec.rb
  spec/forms/course_years_form_spec.rb
Labels: deploy

#2611 [4296] News and updates about Apply integration
  db/service_updates.yml
Labels: deploy

#2612 4296 News and updates grammar error fix
  db/service_updates.yml
Labels: deploy

#2616 Add missing end bracket draft Apply trainees
  config/locales/en.yml
Labels: deploy

#2617 Correct casing for 'Trainee Data'
  config/locales/en.yml
Labels: deploy

#2618 Remove 'Return to drafts' link on Trainee data
  app/views/trainees/apply_applications/trainee_data/edit.html.erb
Labels: deploy

#2607 [4399] Run Trainees::Update on to set academic cycles on awarded and withdrawn trainees
  app/forms/withdrawal_form.rb
  app/jobs/dqt/recommend_for_award_job.rb
  app/jobs/dqt/retrieve_award_job.rb
  app/services/trainees/update.rb
  app/services/trainees/withdraw.rb
  lib/tasks/backfill_missing_award_dates.rake
  spec/forms/withdrawal_form_spec.rb
  spec/jobs/dqt/recommend_for_award_job_spec.rb
  spec/jobs/dqt/retrieve_award_job_spec.rb
  spec/services/trainees/withdraw_spec.rb
Labels: deploy

#2635 Removing sentence in news and updates about HESA
  db/service_updates.yml
Labels: deploy

#2636 [4539] Handle multiple disabilities from HESA and 'Development condition' option
  app/lib/hesa/code_sets/disabilities.rb
  app/lib/hesa/parsers/itt_record.rb
  app/services/trainees/create_from_hesa.rb
  config/initializers/diversity_enums.rb
  db/data/20220812114513_update_disabilities.rb
  spec/lib/hesa/parsers/itt_record_spec.rb
  spec/services/trainees/create_from_hesa_spec.rb
  spec/support/fixtures/hesa/itt_record.xml
Labels: deploy

#2632 [4435] Updates to register code from changes to HESA ITT records
  app/lib/hesa/code_sets/age_ranges.rb
  app/lib/hesa/code_sets/bursary_levels.rb
  app/lib/hesa/code_sets/countries.rb
  app/lib/hesa/code_sets/course_subjects.rb
  app/lib/hesa/code_sets/disabilities.rb
  app/lib/hesa/code_sets/ethnicities.rb
  app/lib/hesa/code_sets/fund_codes.rb
  app/lib/hesa/code_sets/genders.rb
  app/lib/hesa/code_sets/itt_aims.rb
  app/lib/hesa/code_sets/itt_qualification_aims.rb
  app/lib/hesa/code_sets/modes.rb
  app/lib/hesa/code_sets/reasons_for_leaving_course.rb
  app/lib/hesa/code_sets/service_leavers.rb
  app/lib/hesa/code_sets/sexes.rb
  app/lib/hesa/code_sets/study_length_units.rb
  app/lib/hesa/code_sets/study_modes.rb
  app/lib/hesa/code_sets/training_initiatives.rb
  app/lib/hesa/code_sets/training_routes.rb
  app/lib/hesa/parsers/itt_record.rb
  app/models/trainee.rb
  app/services/trainees/calculate_itt_end_date.rb
  app/services/trainees/create_from_hesa.rb
  app/services/trainees/map_state_from_hesa.rb
  app/views/trainees/personal_details/edit.html.erb
  config/initializers/diversity_enums.rb
  config/locales/en.yml
  config/settings.yml
  config/settings/production.yml
  db/data/20220812114513_update_disabilities.rb
  spec/factories/hesa/metadata.rb
  spec/lib/hesa/parsers/itt_record_spec.rb
  spec/models/trainee_spec.rb
  spec/services/trainees/create_from_hesa_spec.rb
  spec/services/trainees/map_state_from_hesa_spec.rb
  spec/support/fixtures/hesa/itt_record.xml
Labels: deploy

#2638 [4534] Add record_source field to trainee
  app/components/application_record_card/view.rb
  app/components/record_details/view.rb
  app/controllers/trainees_controller.rb
  app/jobs/hesa/retrieve_collection_job.rb
  app/jobs/hesa/retrieve_job.rb
  app/jobs/hesa/retrieve_trn_data_job.rb
  app/models/trainee.rb
  app/services/exports/trainee_search_data.rb
  app/services/trainees/create_from_apply.rb
  app/services/trainees/create_from_dttp.rb
  app/services/trainees/create_from_hesa.rb
  app/views/trainees/training_routes/_form_fields.html.erb
  config/analytics.yml
  config/initializers/record_sources.rb
  config/rubocop/rspec.yml
  db/migrate/20220812143158_add_record_source_field_to_trainees.rb
  db/schema.rb
  lib/tasks/example_data.rake
  spec/factories/trainees.rb
  spec/features/trainee_actions/creating_a_new_trainee_spec.rb
  spec/jobs/hesa/retrieve_collection_job_spec.rb
  spec/jobs/hesa/retrieve_trn_data_job_spec.rb
  spec/models/trainee_spec.rb
  spec/services/trainees/create_from_apply_spec.rb
  spec/services/trainees/create_from_dttp_spec.rb
  spec/services/trainees/create_from_hesa_spec.rb
Labels: deploy

#2640 [4541] Hide trainees when they have only been requested for TRN via HESA
  app/services/trainees/filter.rb
  spec/services/trainees/filter_spec.rb
Labels: deploy

#2633 Create analysis database for TAD/Funding queries
  .github/workflows/database-backup.yml
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace-variables/production.tfvars.json
Labels: DevOps

#2653 [4541] Hide HESA TRN data trainees
  app/services/trainees/filter.rb
  lib/tasks/example_data.rake
  spec/factories/trainees.rb
  spec/services/trainees/filter_spec.rb
Labels: deploy

#2669 Update Terraform StatusCake provider to 2.0.3
  docs/disaster-recovery.md
  terraform/.terraform.lock.hcl
  terraform/modules/statuscake/provider.tf
  terraform/terraform.tf
Labels: DevOps, deploy

#2686 [4494] Create academic cycles in the future
  config/initializers/academic_cycles.rb
  db/data/20220830134128_add_future_academic_cycles.rb
Labels: deploy
