Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-01, with the labels that each got.

#1819 [3311] Enable draft records page
  app/components/status_tag/view.rb
  app/controllers/pages_controller.rb
  app/controllers/trainees_controller.rb
  app/helpers/navigation_helper.rb
  app/helpers/trainee_helper.rb
  app/view_objects/home_view.rb
  app/views/drafts/index.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/trainees/_filters.html.erb
  app/views/trainees/_results.html.erb
  app/views/trainees/check_details/show.html.erb
  app/views/trainees/index.html.erb
  app/views/trainees/new.html.erb
  app/views/trainees/review_drafts/show.html.erb
  config/locales/en.yml
  db/service_updates.yml
  spec/features/trainee_actions/filtering_trainees_spec.rb
  spec/features/trainee_actions/submit_for_trn_spec.rb
  spec/features/trainee_actions/viewing_an_existing_trainee_spec.rb
  spec/helpers/trainee_helper_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/trainees/index.rb
Labels: deploy

#1859 [3340] Fix empty item shown in autocomplete
  app/components/form_components/autocomplete/script.js
  app/webpacker/scripts/autocomplete/stop_words.spec.js
  app/webpacker/scripts/live_filter.js
  app/webpacker/scripts/live_filter.spec.js
Labels: deploy

#1868 [3374] Provider users many to many
  app/components/personas/view.html.erb
  app/controllers/system_admin/imports/users_controller.rb
  app/controllers/system_admin/users_controller.rb
  app/controllers/trainees_controller.rb
  app/models/provider.rb
  app/models/provider_user.rb
  app/models/user.rb
  app/policies/trainee_policy.rb
  app/views/pages/home.html.erb
  app/views/trainees/training_routes/_form_fields.html.erb
  db/data/20220104160549_update_provider_users.rb
  db/migrate/20220104155959_create_provider_users.rb
  db/schema.rb
  lib/tasks/example_data.rake
  spec/components/personas/view_preview.rb
  spec/components/personas/view_spec.rb
  spec/controllers/pages_controller_spec.rb
  spec/controllers/trainees/award_recommendations_controller_spec.rb
  spec/controllers/trainees/confirm_deferrals_controller_spec.rb
  spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
  spec/controllers/trainees/confirm_withdrawals_controller_spec.rb
  spec/controllers/trainees/degrees/type_controller_spec.rb
  spec/controllers/trainees/degrees_controller_spec.rb
  spec/controllers/trainees/lead_schools_controller_spec.rb
  spec/controllers/trainees/personal_details_controller_spec.rb
  spec/controllers/trainees/subject_specialisms_controller_spec.rb
  spec/controllers/trainees/training_details_controller_spec.rb
  spec/controllers/trainees_controller_spec.rb
  spec/controllers/trn_submissions_controller_spec.rb
  spec/factories/provider_users.rb
  spec/factories/users.rb
  spec/features/end_to_end/teach_first_journey_spec.rb
  spec/features/form_sections/personal_and_education_details/degrees/delete_degree_spec.rb
  spec/features/form_sections/personal_and_education_details/degrees/editing_degree_spec.rb
  spec/features/form_sections/personal_and_education_details/diversities/edit_ethnic_background_spec.rb
  spec/features/form_sections/personal_and_education_details/diversities/edit_ethnic_group_spec.rb
  spec/features/system_admin/users/creating_a_new_user_spec.rb
  spec/features/system_admin/users/deleting_a_user_spec.rb
  spec/features/system_admin/users/updating_a_user_spec.rb
  spec/features/system_admin/users/viewing_users_spec.rb
  spec/features/trainee_actions/filtering_trainees_spec.rb
  spec/features/trainee_actions/submit_for_trn_spec.rb
  spec/models/provider_user_spec.rb
  spec/models/user_spec.rb
  spec/policies/trainee_policy_spec.rb
  spec/support/features/trainee_steps.rb
  spec/view_objects/system_admin/users_view_spec.rb
Labels: deploy

#1850 [3373] lead school page
  app/controllers/system_admin/lead_schools_controller.rb
  app/views/system_admin/lead_schools/index.html.erb
  app/views/system_admin/lead_schools/show.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/lead_schools/show_lead_school_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/lead_schools/show.rb
Labels: deploy

#1869 show start date when trainee withdraws
  app/components/withdrawal_details/view.html.erb
  app/components/withdrawal_details/view.rb
  config/locales/en.yml
  spec/components/withdrawal_details/view_spec.rb
Labels: deploy

#1890 [3376] Add user to lead school
  app/components/user_card/view.html.erb
  app/components/user_card/view.rb
  app/controllers/system_admin/lead_schools/users_controller.rb
  app/views/system_admin/dttp_providers/show.html.erb
  app/views/system_admin/dttp_users/index.html.erb
  app/views/system_admin/lead_schools/index.html.erb
  app/views/system_admin/lead_schools/show.html.erb
  app/views/system_admin/lead_schools/users/edit.html.erb
  app/views/system_admin/lead_schools/users/new.html.erb
  app/views/system_admin/providers/show.html.erb
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  spec/factories/lead_school_users.rb
  spec/factories/users.rb
  spec/features/system_admin/lead_schools/users/creating_a_new_user_spec.rb
  spec/features/system_admin/lead_schools/users/viewing_users_spec.rb
  spec/support/page_objects/lead_schools/index.rb
  spec/support/page_objects/lead_schools/show.rb
Labels: deploy

#1896 [3452] ApplicationController#current_user returns UserWithOrganisationContext
  app/controllers/application_controller.rb
  app/lib/user_with_organisation_context.rb
  config/initializers/audited.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/trainees/award_recommendations_controller_spec.rb
  spec/controllers/trainees/confirm_deferrals_controller_spec.rb
  spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
  spec/controllers/trainees/confirm_withdrawals_controller_spec.rb
  spec/controllers/trainees/degrees_controller_spec.rb
  spec/controllers/trainees/lead_schools_controller_spec.rb
  spec/controllers/trainees/start_statuses_controller_spec.rb
  spec/controllers/trainees_controller_spec.rb
  spec/lib/user_with_organisation_context_spec.rb
  spec/support/current_user.rb
  spec/support/features/authentication_steps.rb
Labels: deploy

#1898 Update disable browser autofill code to use data attribute
  app/helpers/application_helper.rb
  app/views/system_admin/providers/edit.html.erb
  app/views/system_admin/providers/new.html.erb
  app/views/system_admin/users/edit.html.erb
  app/views/system_admin/users/new.html.erb
  app/views/trainees/contact_details/edit.html.erb
  app/views/trainees/degrees/_non_uk_degree_form.html.erb
  app/views/trainees/diversity/disability_details/edit.html.erb
  app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
  app/views/trainees/personal_details/edit.html.erb
  app/views/trainees/training_details/edit.html.erb
  app/views/trainees/withdrawals/show.html.erb
  app/webpacker/scripts/global/disable-browser-autofill.js
Labels: deploy

#1877 [3375] Add system admin users tab
  app/controllers/system_admin/users_controller.rb
  app/models/user.rb
  app/policies/provider_policy.rb
  app/views/system_admin/_tab_nav.html.erb
  app/views/system_admin/users/index.html.erb
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  lib/tasks/example_data.rake
  spec/features/system_admin/users/list_users_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/users/index.rb
Labels: deploy

#1880 [3436] Validation on missing data seems slightly broken
  app/components/collapsed_section/view.html.erb
  app/components/collapsed_section/view.rb
  app/components/sections/view.rb
  app/view_objects/apply_invalid_data_view.rb
  config/locales/en.yml
  lib/tasks/example_data.rake
  spec/factories/trainees.rb
  spec/view_objects/apply_invalid_data_view_spec.rb
Labels: deploy

#1900 [1009] Snags with seed data
  app/views/trainees/_results.html.erb
  db/seeds.rb
  lib/tasks/example_data.rake
  spec/factories/trainees.rb
Labels: deploy

#1874 [3374] Provider users many to many - remove old provider column from users
  db/migrate/20220106101133_remove_provider_from_users.rb
  db/schema.rb
  spec/components/user_card/view_preview.rb
Labels: DO NOT MERGE

#1930 Service updates for start dates
  db/service_updates.yml
Labels: deploy

#1924 [498] Deprecate GitHub actions keyvault yaml secret
  .github/workflows/deploy.yml
Labels: DevOps, deploy

#1921 3484 s imported trainee filter
  app/controllers/base_trainee_controller.rb
  app/models/trainee.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/views/trainees/_filters.html.erb
  config/locales/en.yml
  spec/factories/trainees.rb
  spec/features/trainee_actions/filtering_trainees_spec.rb
  spec/models/trainee_spec.rb
  spec/services/trainees/filter_spec.rb
  spec/support/page_objects/trainees/index.rb
Labels: deploy

#1918 [3490] HESA records don’t have an address
  app/components/contact_details/view.rb
  app/forms/contact_details_form.rb
  app/views/trainees/contact_details/edit.html.erb
  spec/components/contact_details/view_spec.rb
  spec/forms/contact_details_form_spec.rb
Labels: deploy

#1919 [3502] Fix: ethnicity/diversity not mentioned in the missing data banner
  app/components/apply_applications/trainee_data/view.rb
  app/controllers/trainees/apply_applications/trainee_data_controller.rb
  app/forms/apply_applications/trainee_data_form.rb
  app/forms/degree_form.rb
  app/forms/degrees_form.rb
  app/forms/diversities/form_validator.rb
  app/view_objects/apply_applications/invalid_degree_view.rb
  app/view_objects/apply_applications/invalid_trainee_data_view.rb
  app/view_objects/apply_invalid_data_view.rb
  app/views/trainees/degrees/_non_uk_degree_form.html.erb
  app/views/trainees/degrees/_uk_degree_form.html.erb
  spec/components/review_summary/view_spec.rb
  spec/factories/apply_applications.rb
  spec/factories/trainees.rb
  spec/features/form_sections/personal_and_education_details/reviewing_apply_trainee_data_spec.rb
  spec/forms/degree_form_spec.rb
  spec/view_objects/apply_application/invalid_degree_view_spec.rb
  spec/view_objects/apply_application/invalid_trainee_data_view_spec.rb
  spec/view_objects/apply_invalid_data_view_spec.rb
Labels: deploy

#1959 [3528] Add H1 provider name to draft and registered trainee index pages
  app/views/drafts/index.html.erb
  app/views/trainees/index.html.erb
  spec/features/trainee_actions/filtering_trainees_spec.rb
Labels: deploy

#1931 [3489] HESA records don’t have an ITT end date
  app/components/course_details/view.rb
  app/forms/course_details_form.rb
  app/forms/itt_dates_form.rb
  app/views/trainees/course_details/edit.html.erb
  app/views/trainees/itt_dates/edit.html.erb
  spec/components/course_details/view_spec.rb
  spec/forms/course_details_form_spec.rb
Labels: deploy

#1958 [3500] Do not prompt for missing data on completed records
  app/helpers/mappable_field_helper.rb
  app/view_objects/mappable_field_row.rb
  app/view_objects/missing_data_banner_view.rb
  spec/components/mappable_summary/view_spec.rb
  spec/view_objects/mappable_field_row_spec.rb
  spec/view_objects/missing_data_banner_view_spec.rb
Labels: deploy

#1962 [2581] Use a canonical list of nationalities in seed data
  spec/factories/nationalities.rb
Labels: deploy
