Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-06, with the labels that each got.

#2387 [4180] Update example_data.rake to include funding information
  config/initializers/personas.rb
  lib/tasks/example_data.rake
  spec/factories/funding/payment_schedule_rows.rb
  spec/factories/funding/payment_schedules.rb
  spec/factories/funding/trainee_summaries.rb
  spec/factories/funding/trainee_summary_rows.rb
  spec/factories/schools.rb
Labels: deploy

#2397 [4189] Payment schedule accordion behaviour
  app/view_objects/funding/payment_schedule_view.rb
  app/views/funding/payment_schedules/_month_breakdown.html.erb
  app/views/funding/payment_schedules/show.html.erb
  spec/view_objects/funding/payment_schedule_view_spec.rb
Labels: deploy

#2392 [4183] Trainee summary view bugs
  app/view_objects/funding/trainee_summary_view.rb
  app/views/funding/_navigation.html.erb
  app/views/funding/payment_schedules/show.html.erb
  app/views/funding/trainee_summaries/_tiered_bursaries.html.erb
  app/views/funding/trainee_summaries/show.html.erb
  config/locales/en.yml
  spec/view_objects/funding/trainee_summary_view_spec.rb
Labels: deploy

#2393 [4188] Payment schedule view bugs
  app/view_objects/funding/payment_schedule_view.rb
  app/views/funding/payment_schedules/_month_breakdown.html.erb
  app/views/funding/payment_schedules/show.html.erb
  config/locales/en.yml
Labels: deploy

#2400 [4186] Admin funding view
  app/controllers/funding/payment_schedules_controller.rb
  app/controllers/funding/trainee_summaries_controller.rb
  app/controllers/system_admin/funding/payment_schedules_controller.rb
  app/controllers/system_admin/funding/trainee_summaries_controller.rb
  app/helpers/users_helper.rb
  app/view_objects/funding/navigation_view.rb
  app/views/funding/_navigation.html.erb
  app/views/funding/payment_schedules/show.html.erb
  app/views/funding/trainee_summaries/show.html.erb
  app/views/layouts/application.html.erb
  app/views/system_admin/lead_schools/show.html.erb
  app/views/system_admin/providers/show.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/funding/viewing_lead_schools_funding_spec.rb
  spec/features/system_admin/funding/viewing_providers_funding_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/lead_schools/show.rb
  spec/support/page_objects/providers/show.rb
  spec/support/page_objects/system_admin/funding/lead_schools_payment_schedule.rb
  spec/support/page_objects/system_admin/funding/lead_schools_trainee_summary.rb
  spec/support/page_objects/system_admin/funding/providers_payment_schedule.rb
  spec/support/page_objects/system_admin/funding/providers_trainee_summary.rb
Labels: deploy

#2403 [4216] Remove reference to published course if subject specialism is changed manually
  app/forms/course_details_form.rb
  spec/forms/course_details_form_spec.rb
Labels: deploy

#2401 [4185] Export for payment schedule
  app/controllers/funding/payment_schedules_controller.rb
  app/services/exports/funding_schedule_data.rb
  app/views/funding/payment_schedules/show.html.erb
  config/locales/en.yml
  spec/features/funding/payment_schedule_spec.rb
  spec/services/exports/funding_schedule_data_spec.rb
  spec/support/page_objects/funding/payment_schedule.rb
Labels: deploy

#2411 [4202] Add title_tag attribute to our ServiceUpdate component
  app/components/service_update/view.html.erb
  app/components/service_update/view.rb
  app/views/pages/start.html.erb
  spec/components/service_update/view_spec.rb
Labels: deploy

#2409 [4182] export for trainee summary
  app/controllers/funding/trainee_summaries_controller.rb
  app/services/exports/funding_trainee_summary_data.rb
  app/view_objects/funding/navigation_view.rb
  app/views/funding/payment_schedules/show.html.erb
  app/views/funding/trainee_summaries/show.html.erb
  config/locales/en.yml
  spec/factories/funding/trainee_summary_rows.rb
  spec/features/funding/trainee_summary_spec.rb
  spec/services/exports/funding_trainee_summary_data_spec.rb
  spec/support/page_objects/funding/trainee_summary.rb
Labels: deploy

#2415 [4021] Preserve selection of degree type when navigating back
  app/controllers/trainees/degrees/type_controller.rb
  app/views/trainees/degrees/new.html.erb
  spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
  spec/support/page_objects/trainees/new_degree_details.rb
Labels: deploy

#2427 [4245] remove .html from trainee summary path
  app/view_objects/funding/navigation_view.rb
Labels: deploy

#2424 [4191] Change /privacy-policy to /privacy-notice
  app/controllers/pages_controller.rb
  app/views/layouts/application.html.erb
  app/views/pages/privacy_notice.html.erb
  config/locales/en.yml
  config/locales/pages/data_sharing_agreement/en.yml
  config/locales/pages/privacy_policy/en.yml
  config/routes.rb
  spec/features/static_pages_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/base.rb
Labels: deploy

#2414 Updated analytics.yml file
  config/analytics.yml
Labels: deploy

#2432 [xxx] Remove double back link from trainee summary
  app/views/funding/trainee_summaries/show.html.erb
Labels: deploy

#2436 [4246] funding csv exports
  app/helpers/exports_helper.rb
  app/models/funding/payment_schedule.rb
  app/services/exports/funding_schedule_data.rb
  app/services/exports/funding_trainee_summary_data.rb
  app/services/exports/trainee_search_data.rb
  spec/models/funding/payment_schedule_spec.rb
  spec/services/exports/funding_schedule_data_spec.rb
  spec/services/exports/funding_trainee_summary_data_spec.rb
Labels: deploy

#2435 DR document updates and add review testing
  Makefile
  bin/backup-review-database
  bin/upload-review-backup
  docs/disaster-recovery.md
Labels: DevOps, deploy

#2402 [4201] Restrict access to funding link until we have an academic year
  app/helpers/funding_helper.rb
  spec/components/sections/view_spec.rb
  spec/factories/trainees.rb
  spec/features/end_to_end/assessment_only_journey_spec.rb
  spec/features/end_to_end/early_years_assessment_only_journey_spec.rb
  spec/features/end_to_end/early_years_postgrad_journey_spec.rb
  spec/features/end_to_end/early_years_salaried_journey_spec.rb
  spec/features/end_to_end/opt_in_undergrad_spec.rb
  spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb
  spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
  spec/features/end_to_end/provider_led_undergrad_journey_spec.rb
  spec/features/end_to_end/school_direct_salaried_journey_spec.rb
  spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb
  spec/features/end_to_end/teach_first_journey_spec.rb
  spec/lib/funding_manager_spec.rb
  spec/support/features/training_route_steps.rb
  spec/support/shared_examples/rendering_the_funding_section.rb
Labels: deploy

#2437 [4254] SetAcademicCycles service
  app/jobs/trainees/set_academic_cycles_job.rb
  app/models/trainee.rb
  app/services/trainees/set_academic_cycles.rb
  app/services/trainees/update.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  spec/factories/academic_cycles.rb
  spec/factories/hesa/metadata.rb
  spec/services/trainees/set_academic_cycles_spec.rb
  spec/services/trainees/update_spec.rb
Labels: deploy

#2451 [4211] Update the Data Sharing Agreement
  config/locales/pages/data_sharing_agreement/en.yml
Labels: deploy

#2454 [4248] Remove the concept of cohorts
  app/controllers/base_trainee_controller.rb
  app/controllers/trainees_controller.rb
  app/jobs/trainees/queue_cohort_updates_job.rb
  app/jobs/trainees/set_cohort_job.rb
  app/models/trainee.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/services/trainees/set_cohort.rb
  app/views/layouts/application.html.erb
  app/views/trainees/_cohort_filter.html.erb
  app/views/trainees/_filters.html.erb
  app/views/trainees/apply_applications/trainee_data/edit.html.erb
  app/views/trainees/check_details/show.html.erb
  app/views/trainees/outcome_details/recommended.html.erb
  app/views/trainees/review_drafts/show.html.erb
  app/views/trn_submissions/show.html.erb
  config/analytics.yml
  config/locales/en.yml
  config/settings.yml
  config/sidekiq_cron_schedule.yml
  db/migrate/20220622105221_remove_cohort_from_trainees.rb
  db/schema.rb
  lib/tasks/example_data.rake
  spec/controllers/trainees_controller_spec.rb
  spec/factories/trainees.rb
  spec/features/trainee_actions/filtering_trainees_by_cohort_spec.rb
  spec/features/trainee_actions/recommending_for_qts_spec.rb
  spec/features/trainee_actions/submit_for_trn_spec.rb
  spec/jobs/trainees/queue_cohort_updates_job_spec.rb
  spec/jobs/trainees/set_cohort_job_spec.rb
  spec/services/trainees/set_cohort_spec.rb
  spec/support/page_objects/trainees/index.rb
Labels: deploy

#2455 [4282] Switch default course year to 2022
  config/settings.yml
  spec/factories/courses.rb
  spec/factories/trainees.rb
Labels: deploy

#2463 [4278] Lookup existing dsi users by UUID at signin
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/sign_out_controller_spec.rb
  spec/services/dfe_sign_in_users/update_spec.rb
Labels: deploy

#2441 [4253] Add filters for start and end academic cycle
  app/controllers/base_trainee_controller.rb
  app/controllers/trainees_controller.rb
  app/helpers/course_details_helper.rb
  app/models/academic_cycle.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/view_objects/academic_year_filter_options.rb
  app/view_objects/start_year_filter_options.rb
  app/views/trainees/_filters.html.erb
  config/initializers/academic_cycles.rb
  config/locales/en.yml
  spec/factories/trainees.rb
  spec/helpers/course_details_helper_spec.rb
  spec/services/trainees/filter_spec.rb
  spec/view_objects/academic_year_filter_options_spec.rb
  spec/view_objects/start_year_filter_options_spec.rb
Labels: DO NOT MERGE, deploy

#2481 [4307] Add hesa_id and hesa_updated_at to trainee export
  app/services/exports/trainee_search_data.rb
  spec/services/exports/trainee_search_data_spec.rb
Labels: deploy
