Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-04, with the labels that each got.

#2141 [3785] Add search by user last name and email
  app/controllers/system_admin/users_controller.rb
  app/views/system_admin/users/index.html.erb
  spec/features/system_admin/users/search_users_spec.rb
  spec/support/page_objects/users/index.rb
Labels: deploy

#2171 [3778] Add some HESA trainees, HEI provider and user to the seed data
  .github/workflows/build-and-deploy.yml
  config/initializers/personas.rb
  lib/tasks/example_data.rake
  spec/factories/trainees.rb
Labels: deploy

#2160 [3798] Bugs with school picking flows part 1/3
  app/controllers/trainees/employing_schools_controller.rb
  app/forms/schools/employing_school_form.rb
  app/forms/schools/form.rb
  app/forms/schools/lead_school_form.rb
  app/views/trainees/employing_schools/_no_results.html.erb
  app/views/trainees/employing_schools/_results.html.erb
  app/views/trainees/lead_schools/_no_results.html.erb
  app/views/trainees/lead_schools/_results.html.erb
  config/locales/en.yml
  spec/support/shared_examples/school_form_validations.rb
Labels: deploy

#2194 [3878] Fix: subject specialism presence validation is broken for updating courses
  app/forms/subject_specialism_form.rb
  app/views/trainees/subject_specialisms/edit.html.erb
  spec/forms/subject_specialism_form_spec.rb
Labels: deploy

#2189 [3896] Guidance page content update
  config/locales/pages/guidance/en.yml
Labels: deploy

#2156 [xxxx] Order publish courses by name for manually added trainees
  app/models/trainee.rb
  spec/models/trainee_spec.rb
Labels: deploy

#2169 [3850] Hide HESA non-editable inset for non-editable trainees
  app/views/layouts/trainee_record.html.erb
Labels: deploy

#2217 Force tables to overflow-x
  app/webpacker/styles/_govuk_overrides.scss
Labels: deploy

#2216 Swap order of action links so it matches visual order
  app/views/trainees/_action_bar.html.erb
  app/webpacker/styles/trainee_list.scss
Labels: deploy

#2215 Remove abbr from hidden content
  config/locales/en.yml
Labels: deploy

#2214 Add page title and use translation file
  app/views/organisations/index.html.erb
  config/locales/en.yml
Labels: deploy

#2200 [3677] Add cohort filter
  app/controllers/base_trainee_controller.rb
  app/controllers/trainees_controller.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/views/layouts/application.html.erb
  app/views/trainees/_cohort_filter.html.erb
  app/views/trainees/_filters.html.erb
  app/views/trainees/apply_applications/trainee_data/edit.html.erb
  app/views/trainees/check_details/show.html.erb
  app/views/trainees/outcome_details/recommended.html.erb
  app/views/trainees/review_drafts/show.html.erb
  app/views/trn_submissions/show.html.erb
  config/locales/en.yml
  lib/tasks/example_data.rake
  spec/controllers/trainees_controller_spec.rb
  spec/factories/trainees.rb
  spec/features/trainee_actions/delete_trainee_spec.rb
  spec/features/trainee_actions/filtering_trainees_by_cohort_spec.rb
  spec/features/trainee_actions/recommending_for_qts_spec.rb
  spec/features/trainee_actions/submit_for_trn_spec.rb
  spec/support/page_objects/trainees/index.rb
Labels: deploy

#2177 Refactor smoke test workflow as a reusable action
  .github/actions/deploy/action.yml
  .github/actions/smoke-test/action.yml
  .github/workflows/smoke-test.yml
Labels: deploy

#2219 [3954] HESA records in Register - Add record source to CSV for record export
  app/services/exports/trainee_search_data.rb
  spec/services/exports/trainee_search_data_spec.rb
Labels: deploy

#2234 Extra text on ‘Hide this message’ button
  app/views/layouts/_cookie_banner.html.erb
  config/locales/pages/cookie_policy/en.yml
Labels: deploy

#2185 Set non-review envs to use job env for dep status
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
Labels: deploy

#2208 [3914] Return complete and incomplete trainees correctly
  app/models/trainee.rb
  app/services/trainees/filter.rb
  spec/features/trainee_actions/filtering_trainees_spec.rb
Labels: deploy

#2237 [xxx] Order provider select alphabetically when adding provider to user in system admin
  app/views/system_admin/user_providers/new.html.erb
Labels: deploy

#2236 [3957] Add dynamic funding guidance link
  app/forms/funding/bursary_form.rb
  app/lib/funding_manager.rb
  app/views/trainees/funding/bursaries/_grant_form.html.erb
  app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
  app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
  config/locales/en.yml
  spec/features/end_to_end/early_years_postgrad_journey_spec.rb
  spec/features/form_sections/teacher_training_data/edit_bursary_spec.rb
  spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
Labels: deploy

#2251 Add concurency to the deploy workflows
  .github/workflows/deploy.yml
Labels: DevOps

#2239 3943 Add read only function for provider users
  app/policies/trainee_policy.rb
  db/migrate/20220407145510_add_read_only_to_users.rb
  db/schema.rb
  spec/policies/trainee_policy_spec.rb
Labels: deploy

#2244 [3976] `Trainees::Update` service
  app/controllers/trainees/course_years_controller.rb
  app/forms/apply_applications/confirm_course_form.rb
  app/forms/apply_applications/trainee_data_form.rb
  app/forms/contact_details_form.rb
  app/forms/course_details_form.rb
  app/forms/course_education_phase_form.rb
  app/forms/diversities/disclosure_form.rb
  app/forms/itt_dates_form.rb
  app/forms/personal_details_form.rb
  app/forms/publish_course_details_form.rb
  app/forms/start_date_verification_form.rb
  app/forms/trainee_form.rb
  app/forms/trainee_start_date_form.rb
  app/forms/trainee_start_status_form.rb
  app/lib/route_data_manager.rb
  app/services/trainees/update.rb
  spec/services/trainees/update_spec.rb
Labels: deploy

#2259 [3972] Update request an account page content
  app/views/request_an_account/index.html.erb
  config/locales/en.yml
Labels: deploy

#2229 [3927] Update privacy policy
  config/locales/en.yml
  config/locales/pages/privacy_policy/en.yml
Labels: deploy

#2273 Delete GitHub environment along with review app
  .github/workflows/delete-review-app.yml
Labels: DevOps, deploy

#2241 [3955] Update to GOV.UK frontend 4.0
  Gemfile
  Gemfile.lock
  app/components/collapsed_section/view.html.erb
  app/components/form_components/autocomplete/style.scss
  app/components/header/view.html.erb
  package.json
  yarn.lock
Labels: deploy

#2280 Add service.gov.uk routes to PaaS
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
Labels: DevOps, deploy

#2267 [4001] Add accreditation_ID to providers
  app/controllers/system_admin/dttp_providers_controller.rb
  app/controllers/system_admin/providers_controller.rb
  app/models/provider.rb
  app/views/system_admin/providers/edit.html.erb
  app/views/system_admin/providers/new.html.erb
  config/locales/en.yml
  db/data/20220422144717_backfill_provider_accreditation_id.rb
  db/migrate/20220420095158_add_accreditation_id_to_provider.rb
  db/schema.rb
  lib/tasks/example_data.rake
  spec/factories/dttp/account.rb
  spec/factories/providers.rb
  spec/features/system_admin/dttp_providers/list_providers_spec.rb
  spec/features/system_admin/providers/creating_a_new_provider_spec.rb
  spec/features/system_admin/providers/editing_a_provider_spec.rb
  spec/support/page_objects/providers/new.rb
Labels: deploy

#2288 [4050] Add data sharing agreement page and link from footer
  app/controllers/pages_controller.rb
  app/views/pages/data_sharing_agreement.html.erb
  app/views/pages/home.html.erb
  config/locales/en.yml
  config/locales/pages/data_sharing_agreement/en.yml
  config/routes.rb
Labels: deploy

#2297 Remove unneeded API_TOKEN_FOR_GITHUB_ACTION refs
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
Labels: deploy

#2304 4064 upload hesa review extension to news and guidance
  app/models/service_update.rb
  app/views/pages/start.html.erb
  db/service_updates.yml
  spec/models/service_update_spec.rb
Labels: deploy
