Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-05, with the labels that each got.

#2321 Fixed outputs on build-nocache workflow
  .github/workflows/build-nocache.yml
Labels: DevOps

#2293 [4055] Change QA and Staging to use the service domain
  config/environments/development.rb
  config/initializers/canonical_rails.rb
  config/routes.rb
  config/settings.yml
  config/settings/production.yml
  config/settings/qa.yml
  config/settings/staging.yml
  config/settings/test.yml
  spec/requests/redirect_to_service_gov_uk_spec.rb
  spec/requests/traineeteacherportal_requests_spec.rb
  terraform/modules/paas/variables.tf
Labels: deploy

#2322 [4097] Add service update for HESA integration
  db/service_updates.yml
Labels: deploy

#2311 [4053] Make accreditation_id unique on Provider
  app/models/provider.rb
  db/migrate/20220503114908_add_unique_constraint_to_accrediation_id_on_providers.rb
  db/schema.rb
  spec/features/system_admin/providers/creating_a_new_provider_spec.rb
  spec/features/system_admin/providers/editing_a_provider_spec.rb
Labels: deploy

#2325 Add dr docs data corruption
  Makefile
  docs/disaster-recovery.md
  docs/maintenance-mode.md
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
Labels: deploy

#2340 Fix workflow notification messages
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
Labels: DevOps

#2337 [579] Update register environment url in workflow
  .github/actions/deploy/action.yml
  Makefile
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace-variables/dttpimport.tfvars.json
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: DevOps, deploy

#2343 [4024] news and updates - new domain
  db/service_updates.yml
Labels: deploy

#2350 Fix review app deployment URL
  .github/actions/deploy/action.yml
Labels: DevOps, deploy

#2339 Add dr docs database loss
  .github/workflows/database-backup.yml
  .gitignore
  .tool-versions
  Makefile
  bin/download-nightly-backup
  bin/restore-nightly-backup
  docs/disaster-recovery.md
Labels: DevOps, deploy

#2361 [585] Fix delete review app workflow
  .github/workflows/delete-review-app.yml
Labels: DevOps

#2300 Changes for register service domain
  Makefile
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: DevOps

#2353 [4106] Add data migration to correct the academic cycle dates
  app/forms/course_details_form.rb
  db/data/20220517120014_update_academic_cycle_dates.rb
  spec/factories/academic_cycles.rb
Labels: deploy

#2349 [4054] Update feedback survey link
  app/views/layouts/application.html.erb
  app/views/trainees/outcome_details/recommended.html.erb
  app/views/trn_submissions/show.html.erb
  config/settings.yml
  config/settings/production.yml
Labels: deploy

#2369 [4047] Content update request account
  app/views/request_an_account/index.html.erb
  config/locales/en.yml
Labels: deploy

#2355 [4080] Funding payment schedule page
  app/controllers/funding/monthly_payments_controller.rb
  app/controllers/funding/payment_schedules_controller.rb
  app/models/academic_cycle.rb
  app/view_objects/funding/payment_schedule_view.rb
  app/views/funding/monthly_payments/show.html.erb
  app/views/funding/payment_schedules/_month_breakdown.html.erb
  app/views/funding/payment_schedules/show.html.erb
  app/views/layouts/application.html.erb
  app/webpacker/styles/_govuk_overrides.scss
  config/locales/en.yml
  config/routes.rb
  config/settings/test.yml
  spec/features/funding/payment_schedule_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/funding/payment_schedule.rb
  spec/view_objects/funding/payment_schedule_view_spec.rb
Labels: deploy

#2345 [4081] Trainee summary page UI
  app/controllers/funding/trainee_summaries_controller.rb
  app/view_objects/funding/trainee_summary_view.rb
  app/views/funding/trainee_summaries/_bursaries.html.erb
  app/views/funding/trainee_summaries/_grants.html.erb
  app/views/funding/trainee_summaries/_scholarships.html.erb
  app/views/funding/trainee_summaries/_summary.html.erb
  app/views/funding/trainee_summaries/_tiered_bursaries.html.erb
  app/views/funding/trainee_summaries/show.html.erb
  config/locales/en.yml
  spec/features/funding/trainee_summary_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/funding/trainee_summary.rb
  spec/view_objects/funding/trainee_summary_view_spec.rb
Labels: deploy

#2374 [4153] Display only two latest updates on start page
  app/models/service_update.rb
Labels: deploy

#2330 [4041] Add funding rules for academic year 22/23
  app/forms/course_details_form.rb
  app/forms/language_specialisms_form.rb
  app/forms/subject_specialism_form.rb
  app/models/trainee.rb
  config/initializers/academic_cycles.rb
  config/initializers/training_routes.rb
  db/data/20220510141655_add_funding_methods_for20222023.rb
  db/seeds.rb
  spec/models/trainee_spec.rb
Labels: deploy

#2375 [4022] Fix page heading / title mismatches
  app/views/pages/accessibility.html.erb
  app/views/pages/check_data.html.erb
  app/views/pages/guidance.html.erb
  app/views/pages/home.html.erb
  app/views/sign_in/index.html.erb
  app/views/system_admin/providers/users/delete.html.erb
  app/views/system_admin/providers/users/new.html.erb
  app/views/trainees/confirm_deletes/show.html.erb
  app/views/trainees/course_details/edit.html.erb
  app/views/trainees/course_years/edit.html.erb
  app/views/trainees/degrees/edit.html.erb
  app/views/trainees/degrees/new.html.erb
  app/views/trainees/forbidden_withdrawals/show.html.erb
  app/views/trainees/language_specialisms/edit.html.erb
  app/views/trainees/outcome_details/confirm.html.erb
  app/views/trainees/publish_course_details/edit.html.erb
  app/views/trainees/subject_specialisms/edit.html.erb
  app/views/trainees/training_details/edit.html.erb
  config/locales/en.yml
  spec/features/auth/sign_in_page_spec.rb
Labels: deploy

#2376 Add SNYK scan to build workflow
  .github/workflows/build-and-deploy.yml
Labels: DevOps

#2391 Tweak margin bottom on summary cards so there's less whitespace
  app/components/summary_card/style.scss
Labels: deploy

#2379 [4052] Wording change 'Privacy policy' to 'Privacy notice'
  app/views/layouts/application.html.erb
  config/locales/en.yml
  config/locales/pages/privacy_policy/en.yml
  spec/support/page_objects/start.rb
Labels: deploy
