Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-03, with the labels that each got.

#2064 [3552] Update accessibility statement
  config/locales/en.yml
  config/locales/pages/accessibility/en.yml
Labels: deploy

#2073 [3682] Improve seeded Apply drafts
  lib/tasks/example_data.rake
Labels: deploy

#2070 Remove db:seed and example_data:generate from review app start command
  .github/workflows/deploy.yml
  db/seeds.rb
  lib/tasks/example_data.rake
  spec/factories/trainees.rb
  terraform/modules/paas/variables.tf
Labels: deploy

#2079 [3710] Fix snags with seed data
  lib/tasks/example_data.rake
  spec/controllers/trainees/personal_details_controller_spec.rb
  spec/controllers/trainees/training_details_controller_spec.rb
  spec/factories/trainees.rb
  spec/features/form_sections/personal_and_education_details/degrees/editing_degree_spec.rb
  spec/forms/submissions/trn_validator_spec.rb
  spec/services/find_empty_trainees_spec.rb
  spec/services/trainees/filter_spec.rb
  spec/support/shared_examples/rendering_the_funding_section.rb
Labels: deploy

#2091 [3756] Add email uniqueness validation and db constraint
  app/models/user.rb
  config/locales/en.yml
  db/migrate/20220302160415_add_uniqueness_to_user_email.rb
  db/schema.rb
  spec/components/user_card/view_preview.rb
  spec/models/user_spec.rb
Labels: deploy

#2081 [3744] Lead school user should not be able to see gender, nationality or diversity details
  app/components/personal_details/view.rb
  app/helpers/organisation_helper.rb
  app/helpers/users_helper.rb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/trainees/personal_details/show.html.erb
  spec/helpers/users_helper_spec.rb
  spec/views/trainees/personal_details/show.html.erb_spec.rb
Labels: deploy

#2082 [3746] Obscure some usernames from the timeline
  app/controllers/trainees/timelines_controller.rb
  app/services/trainees/create_timeline.rb
  app/services/trainees/create_timeline_events.rb
  spec/services/trainees/create_timeline_events_spec.rb
  spec/services/trainees/create_timeline_spec.rb
Labels: deploy

#2083 Refactor deployment workflows
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
Labels: DevOps, deploy

#2026 [3547] Add Start Year Filter for Historic Trainees
  app/components/application_record_card/view.html.erb
  app/components/application_record_card/view.rb
  app/controllers/base_trainee_controller.rb
  app/controllers/trainees_controller.rb
  app/helpers/course_details_helper.rb
  app/models/academic_cycle.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/view_objects/start_year_filter_options.rb
  app/views/trainees/_filters.html.erb
  app/webpacker/styles/_govuk_overrides.scss
  config/locales/en.yml
  spec/components/application_record_card/view_spec.rb
  spec/factories/academic_cycles.rb
  spec/helpers/course_details_helper_spec.rb
  spec/models/academic_cycle_spec.rb
  spec/models/trainee_filter_spec.rb
  spec/services/trainees/filter_spec.rb
  spec/view_objects/start_year_filter_options_spec.rb
Labels: deploy

#2114 [3711] HESA records in Register - View only state for HESA records
  app/components/application_record_card/view.rb
  app/policies/trainee_policy.rb
  app/views/layouts/trainee_record.html.erb
  app/views/trainees/_results.html.erb
  spec/components/application_record_card/view_preview.rb
  spec/components/application_record_card/view_spec.rb
  spec/policies/trainee_policy_spec.rb
Labels: deploy

#2118 [3712] hesa records in register content change
  app/models/trainee.rb
  app/policies/trainee_policy.rb
  app/views/layouts/trainee_record.html.erb
  config/locales/en.yml
Labels: deploy

#2125 Added new section to news and updates
  db/service_updates.yml
Labels: deploy

#2106 [3671] Record completion filter hidden for users in lead school context
  app/views/trainees/_filters.html.erb
  app/views/trainees/_record_completion_filter.html.erb
  spec/views/trainees/record_completion.html.erb_spec.rb
Labels: deploy

#2132 Fix: review app not deleted
  .github/workflows/delete-review-app.yml
Labels: DevOps

#2133 Stop deployment status marking deployment inactive
  .github/actions/deploy/action.yml
Labels: deploy

#2137 Remove message about how trainees can be recommended for QTS/EYTS
  config/locales/en.yml
Labels: deploy

#2113 [3530] Improve seed data pt 2
  config/initializers/mappings/allocation_subject_to_specialism_mapping.rb
  config/initializers/mappings/publish_to_allocation_subject_mapping.rb
  lib/tasks/example_data.rake
  spec/factories/courses.rb
  spec/factories/trainees.rb
Labels: deploy

#2140 Add permissions for dependabot package push
  .github/workflows/build-and-deploy.yml
Labels: DevOps, deploy

#2139 Add dttp portal PaaS route for staging
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace-variables/staging.tfvars.json
Labels: DevOps, deploy

#2142 [3833] add start_traineeteacherportal page
  app/controllers/pages_controller.rb
  app/views/pages/start_traineeteacherportal.html.erb
  config/environments/development.rb
  config/initializers/canonical_rails.rb
  config/routes.rb
  config/settings/development.yml
  config/settings/production.yml
  config/settings/qa.yml
  config/settings/staging.yml
  config/settings/test.yml
  spec/controllers/pages_controller_spec.rb
  spec/requests/traineeteacherportal_requests_spec.rb
Labels: deploy

#2149 Fix check on smoke test outcome
  .github/actions/deploy/action.yml
Labels: DevOps, deploy

#2152 [3839] Fix undefined method 'recruitment_cycle_year' for nil:NilClass
  app/controllers/trainees/itt_dates_controller.rb
  spec/controllers/trainees/itt_dates_controller_spec.rb
  spec/factories/courses.rb
Labels: deploy

#2143 [3783] Add autocomplete to the user's lead school form
  app/controllers/system_admin/user_lead_schools_controller.rb
  app/forms/system_admin/user_lead_schools_form.rb
  app/views/system_admin/user_lead_schools/_no_results.html.erb
  app/views/system_admin/user_lead_schools/_results.html.erb
  app/views/system_admin/user_lead_schools/index.html.erb
  app/views/system_admin/user_lead_schools/new.html.erb
  app/views/system_admin/users/show.html.erb
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/users/add_lead_school.rb
  spec/support/page_objects/users/lead_schools.rb
Labels: deploy

#2134 3832 Redirect users with no organisations yet
  app/controllers/pages_controller.rb
  app/controllers/sessions_controller.rb
  app/lib/user_with_organisation_context.rb
  app/views/organisations/index.html.erb
  config/locales/en.yml
  config/locales/pages/no_organisation/en.yml
  spec/factories/users.rb
  spec/features/organisation_contexts_spec.rb
  spec/lib/user_with_organisation_context_spec.rb
Labels: deploy

#2157 Fix libretls vulnerability CVE-2022-0778
  Dockerfile
Labels: DevOps

#2144 [3780] show record source for admins
  app/components/application_record_card/view.html.erb
  app/components/application_record_card/view.rb
  app/components/record_details/view.rb
  app/controllers/base_trainee_controller.rb
  app/models/trainee.rb
  app/models/trainee_filter.rb
  app/services/trainees/filter.rb
  app/views/trainees/_filters.html.erb
  app/views/trainees/_record_source_filter.html.erb
  app/views/trainees/show.html.erb
  config/locales/en.yml
  spec/components/application_record_card/view_spec.rb
  spec/components/record_details/view_spec.rb
  spec/factories/trainees.rb
  spec/features/trainee_actions/filtering_trainees_spec.rb
  spec/models/trainee_spec.rb
Labels: deploy

#2166 Add DTTP portal route to PaaS for register-production
  terraform/workspace-variables/production.tfvars.json
Labels: DevOps

#2174 [3864] Remove existing 'delete user' functionality
  app/components/user_card/view.html.erb
  app/components/user_card/view.rb
  app/controllers/system_admin/providers/users_controller.rb
  app/views/system_admin/dttp_providers/show.html.erb
  app/views/system_admin/dttp_users/index.html.erb
  app/views/system_admin/providers/show.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/users/deleting_a_user_spec.rb
Labels: deploy

#2170 [3849] Strip trailing leading whitespace from address fields
  app/models/degree.rb
  app/models/trainee.rb
  app/models/trainee_disability.rb
Labels: deploy

#2183 [3857] Update content for dttp-replaced page
  app/controllers/pages_controller.rb
  app/views/pages/dttp_replaced.html.erb
  app/views/pages/start_traineeteacherportal.html.erb
  config/locales/en.yml
  config/locales/pages/dttp_replaced/en.yml
  config/routes.rb
  spec/controllers/pages_controller_spec.rb
  spec/requests/traineeteacherportal_requests_spec.rb
Labels: deploy

#2180 [3854] Hide funding row for years we don't know the funding rules
  app/components/funding/view.rb
  app/lib/funding_manager.rb
  app/models/trainee.rb
  spec/components/funding/view_spec.rb
  spec/models/trainee_spec.rb
Labels: deploy

#2186 [3887] Remove the 'other' option from the routes page
  app/controllers/trainees/not_supported_routes_controller.rb
  app/controllers/trainees/training_routes_controller.rb
  app/controllers/trainees_controller.rb
  app/helpers/application_helper.rb
  app/views/trainees/not_supported_route.html.erb
  app/views/trainees/training_routes/_form_fields.html.erb
  config/locales/en.yml
  config/routes.rb
  config/settings.yml
  config/settings/dttpimport.yml
  config/settings/production.yml
  config/settings/qa.yml
  config/settings/sandbox.yml
  config/settings/staging.yml
  spec/features/trainee_actions/edit_trainee_training_route_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/trainees/edit_training_route.rb
  spec/support/page_objects/trainees/not_supported_route.rb
Labels: deploy

#2168 [3865] Add UKPRN field to provider forms
  app/controllers/system_admin/providers_controller.rb
  app/models/provider.rb
  app/views/system_admin/providers/edit.html.erb
  app/views/system_admin/providers/new.html.erb
  config/locales/en.yml
  lib/tasks/example_data.rake
  spec/factories/dttp/providers.rb
  spec/features/system_admin/providers/creating_a_new_provider_spec.rb
  spec/models/provider_spec.rb
  spec/support/page_objects/providers/new.rb
Labels: deploy

#2193 [3872] Update content for Request an account page on production
  app/views/request_an_account/index.html.erb
  config/locales/en.yml
Labels: deploy
