Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-07, with the labels that each got.

#2490 [xxx] Move start/end year filter
  app/views/trainees/_filters.html.erb
Labels: deploy

#2460 [4250] Update home page tiles
  .rubocop_todo.yml
  app/components/badges/view.html.erb
  app/components/badges/view.rb
  app/components/status_card/style.scss
  app/components/trainee_status_card/view.rb
  app/models/trainee.rb
  app/view_objects/home_view.rb
  app/views/pages/_badges.html.erb
  app/views/pages/home.html.erb
  config/locales/en.yml
  config/rubocop/rspec.yml
  spec/components/badges/view_preview.rb
  spec/components/badges/view_spec.rb
  spec/components/trainee_status_card/view_preview.rb
  spec/components/trainee_status_card/view_spec.rb
  spec/controllers/pages_controller_spec.rb
  spec/features/end_to_end/assessment_only_journey_spec.rb
  spec/features/end_to_end/early_years_assessment_only_journey_spec.rb
  spec/features/end_to_end/early_years_postgrad_journey_spec.rb
  spec/features/end_to_end/early_years_salaried_journey_spec.rb
  spec/features/end_to_end/opt_in_undergrad_spec.rb
  spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb
  spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
  spec/features/end_to_end/provider_led_undergrad_journey_spec.rb
  spec/features/end_to_end/school_direct_salaried_journey_spec.rb
  spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb
  spec/features/end_to_end/teach_first_journey_spec.rb
  spec/features/form_sections/teacher_training_data/edit_bursary_spec.rb
  spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
  spec/features/funding/payment_schedule_spec.rb
  spec/features/funding/trainee_summary_spec.rb
  spec/features/system_admin/funding/viewing_lead_schools_funding_spec.rb
  spec/features/system_admin/funding/viewing_providers_funding_spec.rb
  spec/support/features/training_route_steps.rb
  spec/view_objects/home_view_spec.rb
Labels: DO NOT MERGE

#2498 [xxx] Add new latest news entry
  db/service_updates.yml
Labels: deploy

#2501 Update the get-image-tag recipe
  Makefile
Labels: DevOps, deploy

#2500 Add end date display for hesa records
  app/components/course_details/view.rb
  config/locales/en.yml
  spec/components/course_details/view_spec.rb
Labels: deploy

#2503 [4312] Update schools.csv to include all known lead schools
  data/schools.csv
  db/data/20220711134906_update_lead_schools.rb
Labels: deploy

#2493 [4330] Pre-select in-training filter
  app/controllers/trainees_controller.rb
  app/helpers/filter_helper.rb
  app/views/trainees/_selected_filters.html.erb
  spec/features/trainee_actions/filtering_trainees_spec.rb
Labels: deploy

#2523 [4376] remove add user button from lead school show page
  app/controllers/system_admin/lead_schools/users_controller.rb
  app/views/system_admin/lead_schools/show.html.erb
  app/views/system_admin/lead_schools/users/new.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/lead_schools/users/creating_a_new_user_spec.rb
Labels: deploy

#2536 [4363] Set EY routes to new EY course education phase
  app/helpers/course_details_helper.rb
  app/models/trainee.rb
  app/services/find_empty_trainees.rb
  app/services/trainees/filter.rb
  app/views/trainees/course_education_phases/edit.html.erb
  config/initializers/course_education_phases.rb
  config/initializers/training_routes.rb
  db/data/20220718091116_backfill_education_phase_on_ey_trainees.rb
  spec/factories/trainees.rb
  spec/models/trainee_spec.rb
Labels: deploy

#2541 [4373] Remove the DTTP providers tab and related code
  app/components/dttp/providers/collection/view.html.erb
  app/components/dttp/providers/collection/view.rb
  app/components/dttp/providers/filters/view.html.erb
  app/components/dttp/providers/filters/view.rb
  app/controllers/system_admin/dttp_providers_controller.rb
  app/models/dttp/provider.rb
  app/policies/dttp/provider_policy.rb
  app/services/system_admin/dttp/providers/filter.rb
  app/views/system_admin/_tab_nav.html.erb
  app/views/system_admin/dttp_providers/index.html.erb
  app/views/system_admin/dttp_providers/show.html.erb
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  spec/features/system_admin/dttp_providers/list_providers_spec.rb
  spec/models/dttp/provider_spec.rb
  spec/policies/dttp/provider_policy_spec.rb
  spec/services/system_admin/dttp/providers/filter_spec.rb
  spec/support/features/page_helpers.rb
Labels: deploy

#2545 [4374] Remove the DTTP users tab on the provider page
  app/components/user_card/view.html.erb
  app/components/user_card/view.rb
  app/controllers/system_admin/dttp_users_controller.rb
  app/controllers/system_admin/imports/users_controller.rb
  app/controllers/system_admin/providers/users_controller.rb
  app/models/dttp/user.rb
  app/view_objects/system_admin/users_view.rb
  app/views/system_admin/_provider_tab_nav.html.erb
  app/views/system_admin/dttp_users/index.html.erb
  app/views/system_admin/providers/show.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/users/viewing_users_spec.rb
  spec/models/dttp/user_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/dttp_users/index.rb
  spec/support/page_objects/providers/show.rb
  spec/view_objects/system_admin/users_view_spec.rb
Labels: deploy

#2550 [4375] Remove the add user button from the provider show page
  app/controllers/system_admin/lead_schools/users_controller.rb
  app/controllers/system_admin/providers/users_controller.rb
  app/views/system_admin/providers/show.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/users/creating_a_new_user_from_provider_page_spec.rb
  spec/features/system_admin/users/updating_a_user_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/lead_schools/show.rb
  spec/support/page_objects/providers/show.rb
Labels: deploy

#2553 [4396] Ensure apply trainee seeds are shown the confirm course page
  lib/tasks/example_data.rake
Labels: deploy

#2556 [4415] Add other option to dfe institutions
  app/helpers/degrees_helper.rb
  app/models/degree.rb
  spec/helpers/degree_helper_spec.rb
Labels: deploy

#2555 [4242] Preserve choice of 'Another course not listed'
  app/forms/publish_course_details_form.rb
  app/views/trainees/publish_course_details/edit.html.erb
Labels: deploy

#2529 Rename dttpimport env to productiondata
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-backup.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
  Makefile
  config/environments/productiondata.rb
  config/settings/productiondata.yml
  terraform/modules/paas/main.tf
  terraform/workspace-variables/app_config.yml
  terraform/workspace-variables/productiondata.tfvars.json
  terraform/workspace-variables/productiondata_backend.tfvars
Labels: DevOps

#2566 Remove statuscake alerts before provider upgrade
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: DevOps

#2564 Upgrade cloudfoundry and statuscake providers.
  terraform/.terraform.lock.hcl
  terraform/modules/paas/main.tf
  terraform/modules/statuscake/main.tf
  terraform/modules/statuscake/provider.tf
  terraform/terraform.tf
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: DevOps

#2575 [4459] Use match and suggestion synonyms in degree autocomplete
  app/helpers/degrees_helper.rb
  spec/helpers/degree_helper_spec.rb
Labels: deploy

#2586 Configures version updates for GitHub Actions
  .github/dependabot.yml
Labels: DevOps

#2587 Delete redis queues for productiondata on deploy
  .github/actions/deploy/action.yml
Labels: DevOps, deploy
