Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-11, with the labels that each got.

#2891 [710] Fix analysis DB refresh job
  .github/workflows/database-backup.yml
Labels: DevOps

#2890 Stop using set-output in check_sp workflow
  .github/actions/deploy/action.yml
Labels: DevOps, deploy, github_actions

#2886 [710] Remove postgres 11 databases
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/productiondata.tfvars.json
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/review.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: DevOps

#2910 [4949] Update privacy policy page
  config/locales/pages/privacy_policy/en.yml
Labels: deploy

#2918 [4971] - Backfill incorrect HESA degrees - previous collection
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/controllers/system_admin/uploads_controller.rb
  app/models/upload.rb
  app/services/hesa/backfill.rb
  app/services/hesa/backfill_degrees.rb
  app/views/system_admin/_tab_nav.html.erb
  app/views/system_admin/uploads/index.html.erb
  app/views/system_admin/uploads/new.html.erb
  app/views/system_admin/uploads/show.html.erb
  config/analytics_blocklist.yml
  config/application.rb
  config/environments/production.rb
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  config/storage.yml
  db/migrate/20221111092526_create_active_storage_tables.active_storage.rb
  db/migrate/20221111095019_create_uploads.rb
  db/migrate/20221111162242_enable_pg_trgm.rb
  db/migrate/20221115162408_add_hesa_id_index_to_trainees.rb
  db/schema.rb
  docs/testing_data_migrations.md
  lib/tasks/backfill_hesa.rake
  spec/factories/uploads.rb
  spec/features/system_admin/uploads/create_spec.rb
  spec/features/system_admin/uploads/delete_spec.rb
  spec/fixtures/files/test.txt
  spec/models/upload_spec.rb
  spec/services/hesa/backfill_degrees_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/fixtures/hesa/itt_record.xml
  spec/support/page_objects/system_admin/uploads/index.rb
  spec/support/page_objects/system_admin/uploads/new.rb
  spec/support/page_objects/system_admin/uploads/show.rb
  spec/support/page_objects/trainees/review_draft.rb
Labels: deploy

#2916 [4907] Add HESA Cyprus codes
  app/controllers/trainees/personal_details_controller.rb
  app/lib/apply_api/code_sets/nationalities.rb
  app/lib/dttp/code_sets/nationalities.rb
  app/models/nationality.rb
  db/data/20221125114348_add_cypriot_nationalities.rb
  spec/models/nationality_spec.rb
Labels: deploy
