Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-09, with the labels that each got.

#2651 [4442] building the report for sign off
  app/controllers/reports_controller.rb
  app/helpers/date_of_the_nth_weekday_helper.rb
  app/helpers/users_helper.rb
  app/policies/user_policy.rb
  app/services/exports/trainee_search_data.rb
  app/services/new_starter_trainees_service.rb
  app/views/layouts/application.html.erb
  app/views/reports/index.html.erb
  app/views/reports/itt_new_starter_data_sign_off.html.erb
  config/routes.rb
  config/settings.yml
  spec/helpers/date_of_the_nth_weekday_helper_spec.rb
  spec/services/exports/trainee_search_data_spec.rb
  spec/services/new_starter_trainees_service_spec.rb
Labels: deploy

#2698 4613-update-for-new-report
  db/service_updates.yml
Labels: deploy

#2706 Remove sandbox env from deployment workflows
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
Labels: DevOps

#2708 Add Terraform check to dependabot
  .github/dependabot.yml
Labels: DevOps

#2719 Remove sandbox env configuration
  Makefile
  app/components/start_page_banner/style.scss
  config/environments/sandbox.rb
  config/rubocop/rails.yml
  config/settings/sandbox.yml
  config/webpacker.yml
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/sandbox_backend.tfvars
Labels: DevOps, deploy

#2731 Add SENTRY_DSN to rspec build tests
  .github/workflows/build-and-deploy.yml
  docker-compose.yml
Labels: DevOps

#2710 22 09 guidance pages
  Gemfile
  Gemfile.lock
  app/controllers/guidance_controller.rb
  app/controllers/pages_controller.rb
  app/views/guidance/_manually_registering_trainees.md
  app/views/guidance/_registering_trainees_through_hesa.md
  app/views/guidance/_withdrawing_or_deferring_a_trainee.md
  app/views/guidance/about_register_trainee_teachers.md
  app/views/guidance/check_data.md
  app/views/guidance/dates_and_deadlines.html.erb
  app/views/guidance/manually_registering_trainees.html.erb
  app/views/guidance/registering_trainees_through_hesa.html.erb
  app/views/guidance/show.html.erb
  app/views/layouts/guidance.html.erb
  app/views/pages/guidance.html.erb
  app/views/pages/home.html.erb
  config/initializers/template_handlers.rb
  config/routes.rb
  lib/template_handlers/markdown.rb
  spec/controllers/guidance_controller_spec.rb
  spec/controllers/pages_controller_spec.rb
Labels: deploy

#2734 [4661] Add additional degree countries or territories and change content for 'degree country'
  .gitignore
  app/lib/dttp/code_sets/countries.rb
  app/views/trainees/degrees/_non_uk_degree_form.html.erb
  lib/tasks/country_autocomplete_graph.rake
  missing-location-graph-from-dttp.json
Labels: ready for review

#2749 [4652] Update dfe-reference gem to bring in new institution
  Gemfile
  Gemfile.lock
Labels: deploy

#2750 [4700] Support: add ability to delete a user
  app/controllers/system_admin/users_controller.rb
  app/views/system_admin/users/delete.html.erb
  app/views/system_admin/users/show.html.erb
  app/webpacker/styles/application.scss
  config/routes/system_admin_routes.rb
  spec/features/system_admin/users/deleting_a_user_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/system_admin/user/delete.rb
  spec/support/page_objects/system_admin/user/index.rb
  spec/support/page_objects/system_admin/user/show.rb
  spec/support/page_objects/users/delete.rb
  spec/support/page_objects/users/index.rb
  spec/support/page_objects/users/show.rb
Labels: deploy

#2743 [4659] Course not showing correct route from Apply
  app/forms/apply_applications/confirm_course_form.rb
  app/forms/concerns/course_form_helpers.rb
  app/forms/course_details_form.rb
  app/forms/publish_course_details_form.rb
  db/data/20220921084032_fix_apply_draft_training_routes.rb
  spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
Labels: deploy

#2744 Move CF and DB github secrets to Azure keyvault
  .github/workflows/database-backup.yml
Labels: DevOps

#2767 Update dates and deadlines from bank holiday
  app/views/guidance/dates_and_deadlines.html.erb
Labels: deploy

#2768 Change to HESA deadline on News and Updates
  db/service_updates.yml
Labels: deploy

#2769 Change system admin to 'Support for Register'
  config/locales/en.yml
Labels: deploy

#2765 Add labels to dependabot
  .github/dependabot.yml
Labels: DevOps

#2758 [4631] Add hesa data mapping page
  app/controllers/guidance_controller.rb
  app/views/guidance/_course_details.html.erb
  app/views/guidance/_database_only.html.erb
  app/views/guidance/_funding.html.erb
  app/views/guidance/_personal_details.html.erb
  app/views/guidance/_schools.html.erb
  app/views/guidance/_trainee_progress.html.erb
  app/views/guidance/hesa_register_data_mapping.html.erb
  app/views/guidance/show.html.erb
  app/views/pages/home.html.erb
  config/routes.rb
  spec/controllers/guidance_controller_spec.rb
Labels: deploy

#2755 [4701] Add ability to remove access to a provider or lead school
  app/controllers/system_admin/lead_schools/accessions_controller.rb
  app/controllers/system_admin/providers/accessions_controller.rb
  app/views/system_admin/lead_schools/accessions/edit.html.erb
  app/views/system_admin/providers/accessions/edit.html.erb
  app/views/system_admin/users/show.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
  spec/features/system_admin/users/add_a_provider_to_user_spec.rb
  spec/features/system_admin/users/creating_a_new_user_spec.rb
  spec/features/system_admin/users/deleting_a_user_spec.rb
  spec/features/system_admin/users/list_users_spec.rb
  spec/features/system_admin/users/removing_user_access_spec.rb
  spec/features/system_admin/users/search_users_spec.rb
  spec/features/system_admin/users/updating_a_user_spec.rb
  spec/models/dttp/users_spec.rb
  spec/models/users_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/system_admin/lead_schools/remove_access_confirmation.rb
  spec/support/page_objects/system_admin/providers/remove_access_confirmation.rb
  spec/support/page_objects/system_admin/user/index.rb
  spec/support/page_objects/system_admin/user/show.rb
  spec/support/page_objects/system_admin/users/delete.rb
  spec/support/page_objects/system_admin/users/edit.rb
  spec/support/page_objects/system_admin/users/index.rb
  spec/support/page_objects/system_admin/users/new.rb
  spec/support/page_objects/system_admin/users/show.rb
  spec/support/page_objects/users/edit.rb
  spec/support/page_objects/users/index.rb
  spec/support/page_objects/users/new.rb
  spec/support/page_objects/users/show.rb
Labels: deploy
