Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-02, with the labels that each got.

#1950 [3492] Fix ITT start date validation
  app/forms/course_details_form.rb
  app/forms/itt_dates_form.rb
  spec/forms/course_details_form_spec.rb
Labels: deploy

#1967 [3501] Autocomplete undefined bug fix
  app/components/form_components/autocomplete/script.js
Labels: deploy

#1970 [3525] Fix back links on User/Provider tab going to the wrong page
  app/helpers/application_helper.rb
  app/views/system_admin/lead_schools/show.html.erb
  app/views/system_admin/providers/show.html.erb
  app/views/system_admin/users/index.html.erb
Labels: deploy

#1985 [3575] Fix: line breaks in service updates yaml don't output line breaks or paragraphs when rendered
  app/components/service_update/view.rb
  db/service_updates.yml
Labels: deploy

#1965 [3498] Fix: ITT start date labelled as missing even though it's present (but invalid)
  app/forms/course_details_form.rb
  app/forms/multi_date_form.rb
  app/forms/personal_details_form.rb
  app/forms/trainee_form.rb
  app/forms/trainee_start_date_form.rb
  app/forms/trainee_start_status_form.rb
  app/lib/invalid_date.rb
Labels: deploy

#1972 [3581] Trainees with invalid TRNs
  app/models/dttp/trainee.rb
  app/services/trainees/create_from_dttp.rb
  spec/factories/dttp/api_trainee.rb
  spec/services/trainees/create_from_dttp_spec.rb
Labels: deploy

#1947 [3377] Add existing user to lead school & provider
  app/controllers/system_admin/user_lead_schools_controller.rb
  app/controllers/system_admin/user_providers_controller.rb
  app/views/system_admin/user_lead_schools/new.html.erb
  app/views/system_admin/user_providers/new.html.erb
  app/views/system_admin/users/index.html.erb
  app/views/system_admin/users/show.html.erb
  config/routes/system_admin_routes.rb
  spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
  spec/features/system_admin/users/add_a_provider_to_user_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/users/add_lead_school.rb
  spec/support/page_objects/users/add_provider.rb
  spec/support/page_objects/users/index.rb
  spec/support/page_objects/users/show.rb
Labels: deploy

#1979 [3577] 'Address is missing' is showing for HESA trainees
  app/forms/contact_details_form.rb
Labels: deploy

#1992 [3598] Add additional_dttp_data field to trainees
  db/migrate/20220204132842_add_additional_dttp_data_to_trainees.rb
  db/schema.rb
  db/scripts/sanitise.sql
Labels: deploy

#1994 [3619] Hide year filters
  app/views/trainees/_filters.html.erb
  config/settings.yml
Labels: deploy

#2002 Improve the display of autocomplete hints
  app/helpers/degrees_helper.rb
  app/lib/dttp/code_sets/degree_types.rb
Labels: deploy

#2013 [3599] Organisation context switching component
  app/components/navigation_bar/style.scss
  app/components/navigation_bar/view.html.erb
  app/components/navigation_bar/view.rb
  app/helpers/organisation_helper.rb
  app/views/layouts/application.html.erb
  config/settings/review.yml
  spec/components/navigation_bar/view_spec.rb
Labels: deploy

#1940 [3382] redirect to confirm page when commencement date before withdra…
  app/components/withdrawal_details/view.rb
  app/controllers/trainees/start_statuses_controller.rb
  app/forms/withdrawal_form.rb
  spec/components/withdrawal_details/view_spec.rb
  spec/controllers/trainees/start_statuses_controller_spec.rb
  spec/features/trainee_actions/withdraw_trainee_spec.rb
  spec/support/page_objects/trainees/confirm_withdrawal.rb
Labels: deploy

#2015 [xxx] Replace Redis.current
  app/services/form_store.rb
  config/initializers/redis.rb
Labels: deploy

#2006 Add weekly cache refresh workflow
  .github/workflows/build-nocache.yml
Labels: DevOps

#2018 Update docker base image to ruby:2.7.5-alpine3.15
  .github/workflows/smoke-test.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  package.json
Labels: DevOps, deploy

#2032 [3456] Draft records last updated sort is inaccurate
  app/components/application_record_card/view.rb
  app/controllers/base_trainee_controller.rb
  app/controllers/trainees_controller.rb
  app/models/trainee.rb
  spec/components/application_record_card/view_preview.rb
  spec/components/application_record_card/view_spec.rb
  spec/models/trainee_spec.rb
Labels: deploy

#2053 Update gmp in Dockerfile to fix vulnerability
  Dockerfile
Labels: DevOps

#2036 [3618] Users not prevented from starting funding section as they should be
  app/lib/funding_manager.rb
  spec/lib/funding_manager_spec.rb
Labels: deploy

#2058 [3601] Update 403/forbidden page content
  app/views/errors/forbidden.html.erb
  config/locales/en.yml
Labels: deploy

#2050 [3672] Lead school welcome email
  app/services/send_welcome_email_service.rb
  config/settings.yml
  spec/services/send_welcome_email_service_spec.rb
Labels: deploy

#2039 [3669] Draft records link and section aren't visible
  app/controllers/drafts_controller.rb
  app/helpers/organisation_helper.rb
  app/policies/user_policy.rb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  config/settings/review.yml
  spec/controllers/pages_controller_spec.rb
  spec/features/trainee_actions/viewing_an_existing_trainee_spec.rb
  spec/helpers/organisation_helper_spec.rb
  spec/policies/user_policy_spec.rb
Labels: deploy

#2062 Migrate to GitHub container registry
  .github/workflows/build-nocache.yml
  .github/workflows/build.yml
  Makefile
  docker-compose.yml
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
Labels: deploy

#2042 [3670] Hide incomplete badge on registered trainees from lead school users
  app/components/application_record_card/view.html.erb
  app/components/application_record_card/view.rb
  app/components/record_header/view.html.erb
  app/components/record_header/view.rb
  app/components/status_tag/view.rb
  app/views/layouts/trainee_record.html.erb
  app/views/trainees/_results.html.erb
  spec/components/record_header/view_spec.rb
  spec/components/status_tag/view_spec.rb
Labels: deploy

#2065 [3527] [3704] bug fixes
  app/services/trainees/create_timeline_events.rb
  app/views/drafts/index.html.erb
  app/views/layouts/application.html.erb
  config/locales/en.yml
  spec/controllers/pages_controller_spec.rb
  spec/features/trainee_actions/submit_for_trn_spec.rb
  spec/support/page_objects/start.rb
Labels: deploy

#2069 Explicitly set text colour on summary card headings
  app/components/summary_card/style.scss
Labels: deploy

#2059 [3673] Show provider details if a user is in a lead school context
  app/components/application_record_card/view.rb
  app/components/record_details/view.rb
  app/views/trainees/_results.html.erb
  app/views/trainees/show.html.erb
  spec/components/application_record_card/view_preview.rb
  spec/components/application_record_card/view_spec.rb
  spec/components/record_details/view_preview.rb
  spec/components/record_details/view_spec.rb
Labels: deploy
