Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2022-10, with the labels that each got.

#2779 Updating guidance to match new csv names
  app/views/guidance/_course_details.html.erb
  app/views/guidance/_personal_details.html.erb
  app/views/guidance/_trainee_progress.html.erb
Labels: deploy

#2791 Update Terraform version to 1.2.8
  .github/actions/deploy/action.yml
  .github/workflows/delete-review-app.yml
  .tool-versions
  terraform/terraform.tf
Labels: DevOps, deploy, terraform

#2809 [4742] Fix: course dates get lost when changing course.
  app/forms/concerns/course_form_helpers.rb
  app/forms/course_details_form.rb
  app/forms/publish_course_details_form.rb
Labels: deploy

#2794 [4742] Fix: funding not cleared properly when changing courses multiple times
  app/forms/publish_course_details_form.rb
  app/forms/subject_specialism_form.rb
  spec/forms/publish_course_details_form_spec.rb
  spec/forms/subject_specialism_form_spec.rb
Labels: deploy

#2819 [4764] Investigate why so many hesa trainees have unmapped grades for degrees
  app/helpers/degrees_helper.rb
  app/services/degrees/dfe_reference.rb
  app/views/trainees/degrees/_uk_degree_form.html.erb
  db/data/20221010142433_backfill_unmapped_hesa_degree_grades.rb
  spec/factories/degrees.rb
  spec/forms/degree_form_spec.rb
  spec/services/degrees/dfe_reference_spec.rb
Labels: deploy

#2832 [4745] Show itt_end_date for HESA trainees
  app/components/course_details/view.rb
  config/locales/en.yml
  spec/components/course_details/view_spec.rb
Labels: deploy

#2833 Remove GitHub action minor version pinning
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
Labels: DevOps, deploy, github_actions

#2851 Link to GIAS service from school picker pages
  config/locales/en.yml
Labels: deploy

#2864 [710] Deploy postgres 13 to productiondata
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/workspace-variables/productiondata.tfvars.json
Labels: DevOps

#2866 [4881] Content changes for sign off deadline extension
  app/views/guidance/dates_and_deadlines.html.erb
  app/views/reports/itt_new_starter_data_sign_off.html.erb
  db/service_updates.yml
Labels: deploy

#2872 [710] Workflow to copy database to postgres 13
  .github/workflows/copy-database-to-postgres13.yml
Labels: DevOps

#2873 [710] Fix copy DB workflow
  .github/workflows/copy-database-to-postgres13.yml
Labels: DevOps

#2875 Point production and productiondata to postgres 13
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/productiondata.tfvars.json
Labels: DevOps

#2881 [710] Migrate qa, staging, analysis to postgres 13
  .github/workflows/database-backup.yml
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: DevOps

#2868 Put paragraphs in 2/3 grid column
  app/views/guidance/_database_only.html.erb
  app/views/guidance/_schools.html.erb
Labels: deploy

#2860 [4858] Remove export link for System admin when more than 100 trainees
  app/components/sort_links/style.scss
  app/components/sort_links/view.rb
  app/controllers/base_trainee_controller.rb
  app/helpers/exports_helper.rb
  app/views/funding/payment_schedules/show.html.erb
  app/views/funding/trainee_summaries/show.html.erb
  app/views/trainees/_action_bar.html.erb
  app/webpacker/styles/trainee_list.scss
  config/settings.yml
  spec/helpers/exports_helper_spec.rb
Labels: deploy

#2884 [710] Migrate postgres analysis to postgres 13
  .github/workflows/database-backup.yml
  terraform/modules/paas/main.tf
Labels: DevOps

#2887 [710] Fix register analysis DB service key
  terraform/modules/paas/main.tf
Labels: DevOps
