Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2023-05, with the labels that each got.

#3238 [5409] Replace feedback collection form url
  config/settings.yml
Labels: deploy

#3228 [5398] - undo withdrawal
  app/components/confirm_undo_withdrawal_details/view.html.erb
  app/components/confirm_undo_withdrawal_details/view.rb
  app/components/withdrawal_details/view.html.erb
  app/controllers/trainees/undo_withdrawals/confirmations_controller.rb
  app/controllers/trainees/undo_withdrawals_controller.rb
  app/forms/undo_withdrawal_form.rb
  app/policies/trainee_policy.rb
  app/services/trainees/create_timeline_events.rb
  app/views/trainees/undo_withdrawals/confirmations/show.html.erb
  app/views/trainees/undo_withdrawals/edit.html.erb
  app/views/trainees/undo_withdrawals/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/trainee_actions/undo_withdraw_trainee_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/trainees/edit_undo_withdrawal.rb
  spec/support/page_objects/trainees/record.rb
  spec/support/page_objects/trainees/show_undo_withdrawal.rb
  spec/support/page_objects/trainees/undo_withdrawal_confirmation.rb
Labels: deploy

#3224 Add aks cheatsheet
  docs/aks-cheatsheet.md
Labels: DevOps, deploy_v2

#3252 Add aks envs
  .github/actions/deploy_v2/action.yml
  .github/actions/smoke-test_v2/action.yml
  Makefile
  config/environments/production_aks.rb
  config/environments/productiondata_aks.rb
  config/environments/qa_aks.rb
  config/environments/review_aks.rb
  config/environments/staging_aks.rb
  config/settings/production_aks.yml
  config/settings/productiondata_aks.yml
  config/settings/qa_aks.yml
  config/settings/review_aks.yml
  config/settings/staging_aks.yml
  global_config/production_aks.sh
  global_config/productiondata_aks.sh
  global_config/qa_aks.sh
  global_config/staging_aks.sh
  terraform/aks/workspace-variables/app_config.yml
  terraform/aks/workspace-variables/production_aks.tfvars.json
  terraform/aks/workspace-variables/production_aks_backend.tfvars
  terraform/aks/workspace-variables/productiondata_aks.tfvars.json
  terraform/aks/workspace-variables/productiondata_aks_backend.tfvars
  terraform/aks/workspace-variables/qa_aks.tfvars.json
  terraform/aks/workspace-variables/qa_aks_backend.tfvars
  terraform/aks/workspace-variables/staging_aks.tfvars.json
  terraform/aks/workspace-variables/staging_aks_backend.tfvars
Labels: DevOps, deploy_v2

#3236 [5418] Swap order of first and last name on csv
  app/models/reports/bulk_recommend_report.rb
  app/views/bulk_update/recommendations_checks/_table.html.erb
  config/analytics_blocklist.yml
  spec/features/bulk_upload/recommending_trainees_spec.rb
Labels: deploy

#3244 [5442] Date QTS award is met is not showing on some awarded trainees
  app/components/award_details/view.html.erb
  app/components/award_details/view.rb
  app/views/trainees/show.html.erb
  spec/components/award_details/view_spec.rb
Labels: deploy

#3256 [5453] - Allow quoted and unquoted HESA_IDs on upload
  app/forms/bulk_update/recommendations_upload_form.rb
  app/services/bulk_update/recommendations_uploads/config.rb
  app/services/bulk_update/recommendations_uploads/create_csv_with_errors.rb
  app/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows.rb
  app/services/bulk_update/recommendations_uploads/row.rb
  app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
  app/services/bulk_update/recommendations_uploads/validate_trainee.rb
  spec/services/bulk_update/recommendations_uploads/validate_csv_spec.rb
Labels: deploy

#3245 [5446] Allow for hesa trainees to be awarded individually
  app/controllers/trainees/outcome_details_controller.rb
Labels: deploy

#3260 181 Post domain migration tidy-up
  terraform/custom_domains/environment_domains/workspace_variables/register_audit.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/register_audit_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/register_pen.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/register_pen_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/register_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/register_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/register_staging.tfvars.json
Labels: DevOps, terraform

#3258 Remove pen and audit env configuration
  .github/workflows/deploy.yml
  Makefile
  config/environments/pen.rb
  config/settings/pen.yml
  terraform/paas/workspace-variables/app_config.yml
  terraform/paas/workspace-variables/pen.tfvars.json
  terraform/paas/workspace-variables/pen_backend.tfvars
Labels: DevOps

#3269 Add console and logs options to make for aks
  Makefile
  docs/aks-cheatsheet.md
  global_config/dv_review_aks.sh
  global_config/production_aks.sh
  global_config/productiondata_aks.sh
  global_config/qa_aks.sh
  global_config/review_aks.sh
  global_config/staging_aks.sh
Labels: DevOps

#3203 5383 Update error messages bulk qts
  app/services/bulk_update/recommendations_uploads/validate_trainee.rb
  config/locales/en.yml
  spec/features/bulk_upload/recommending_trainees_spec.rb
  spec/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_csv_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_file_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
Labels: deploy

#3272 [5454] Allow upload of csv with blank rows
  app/controllers/bulk_update/recommendations_base_controller.rb
  app/models/bulk_update/recommendations_upload.rb
  app/models/bulk_update/recommendations_upload_row.rb
  app/services/bulk_update/recommendations_uploads/row.rb
  app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
  app/services/bulk_update/recommendations_uploads/validate_trainee.rb
  spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
Labels: deploy

#3277 refactor app terraform to use github module
  Makefile
  terraform/aks/application.tf
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/production_aks.tfvars.json
  terraform/aks/workspace-variables/productiondata_aks.tfvars.json
  terraform/aks/workspace-variables/qa_aks.tfvars.json
  terraform/aks/workspace-variables/review_aks.tfvars.json
  terraform/aks/workspace-variables/staging_aks.tfvars.json
  terraform/modules/kubernetes/main.tf
  terraform/modules/kubernetes/outputs.tf
  terraform/modules/kubernetes/variables.tf
  terraform/modules/kubernetes/worker_app.tf
Labels: DevOps, deploy_v2

#3271 [5448] Display placement details when available
  .gitignore
  app/components/placement_details/view.html.erb
  app/components/placement_details/view.rb
  app/components/review_draft/apply_draft/view.html.erb
  app/lib/training_route_manager.rb
  app/models/reports/trainee_report.rb
  app/models/reports/trainees_report.rb
  app/models/trainee.rb
  app/views/trainees/show.html.erb
  config/locales/en.yml
  spec/components/placement_details/view_spec.rb
  spec/components/review_draft/apply_draft/view_spec.rb
  spec/lib/training_route_manager_spec.rb
  spec/models/reports/trainee_report_spec.rb
  spec/models/trainee_spec.rb
  spec/views/trainees/show.html.erb_spec.rb
Labels: deploy

#3281 refactor app config terraform to use module
  terraform/aks/application.tf
  terraform/aks/variables.tf
Labels: deploy_v2

#3278 [338] Manage terraform modules via terrafile
  .gitignore
  .tool-versions
  Makefile
  docs/aks_modules.md
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/cluster_data.tf
  terraform/aks/databases.tf
  terraform/aks/workspace-variables/dv_review_aks_Terrafile
  terraform/aks/workspace-variables/production_aks_Terrafile
  terraform/aks/workspace-variables/productiondata_aks_Terrafile
  terraform/aks/workspace-variables/qa_aks_Terrafile
  terraform/aks/workspace-variables/review_aks_Terrafile
  terraform/aks/workspace-variables/staging_aks_Terrafile
Labels: DevOps, deploy_v2

#3287 [338] Do not run terraform in paas workflow
  Makefile
  global_config/dv_review_aks.sh
  global_config/production_aks.sh
  global_config/productiondata_aks.sh
  global_config/qa_aks.sh
  global_config/register-domain.sh
  global_config/review_aks.sh
  global_config/staging_aks.sh
Labels: DevOps

#3286 Enable aks review app seed data
  .github/actions/deploy_v2/action.yml
  Gemfile
Labels: DevOps, deploy, deploy_v2

#3284 [5489] Get placements for latest hesa collection per trainee
  app/components/placement_details/view.rb
  app/models/hesa/student.rb
  app/models/reports/trainee_report.rb
  app/models/trainee.rb
  spec/components/placement_details/view_spec.rb
  spec/models/reports/trainee_report_spec.rb
  spec/models/trainee_spec.rb
Labels: deploy

#3285 [5473] - BUGFIX - Degree recognition issue
  .gitignore
  db/data/20230518115341_update_institution_on_degrees_with_wrong_mapping.rb
Labels: deploy

#3276 [5449] Allow admins to delete records
  app/components/confirm_trainee_delete/view.html.erb
  app/components/confirm_trainee_delete/view.rb
  app/controllers/system_admin/trainee_deletions/confirmations_controller.rb
  app/controllers/system_admin/trainee_deletions/reasons_controller.rb
  app/forms/system_admin/delete_trainee_form.rb
  app/policies/trainee_policy.rb
  app/services/form_store.rb
  app/services/trainees/filter.rb
  app/views/system_admin/trainee_deletions/confirmations/show.html.erb
  app/views/system_admin/trainee_deletions/reasons/edit.html.erb
  app/views/trainees/admins/show.html.erb
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  spec/features/system_admin/trainees/delete_a_trainee_spec.rb
  spec/forms/system_admin/delete_trainee_form_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/system_admin/trainee_deletions/confirmation.rb
  spec/support/page_objects/system_admin/trainee_deletions/reasons.rb
  spec/support/page_objects/trainees/admin.rb
Labels: deploy

#3289 Create aks qa env
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-v2.yml
  Gemfile
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/production_aks.tfvars.json
  terraform/aks/workspace-variables/productiondata_aks.tfvars.json
  terraform/modules/azure/storage.tf
Labels: DevOps, deploy_v2

#3297 Add aks staging env to workflows
  .github/actions/deploy_v2/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-v2.yml
  .github/workflows/scheduled-aks-db-restore.yml
Labels: DevOps

#3282 [5476] Improve bulk QTS recommend performance
  app/controllers/trainees/award_recommendations_controller.rb
  app/jobs/auditing/trainee_auditor_job.rb
  app/models/reports/trainee_report.rb
  app/services/bulk_update/recommend.rb
  app/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows.rb
  app/services/bulk_update/recommendations_uploads/trainee_lookup.rb
  app/services/bulk_update/recommendations_uploads/validate_trainee.rb
  spec/fixtures/files/bulk_update/recommendations_upload/complete.csv
  spec/jobs/auditing/trainee_auditor_job_spec.rb
  spec/services/bulk_update/recommend_spec.rb
  spec/services/bulk_update/recommendations_uploads/trainee_lookup_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
Labels: deploy, deploy_v2

#3298 [5512] Fix date range bug
  app/models/reports/trainee_report.rb
  spec/models/reports/trainee_report_spec.rb
Labels: deploy, deploy_v2

#3302 Add application probes
  config/environments/production.rb
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/dv_review_aks.tfvars.json
  terraform/aks/workspace-variables/production_aks.tfvars.json
  terraform/aks/workspace-variables/productiondata_aks.tfvars.json
  terraform/aks/workspace-variables/qa_aks.tfvars.json
  terraform/aks/workspace-variables/review_aks.tfvars.json
  terraform/aks/workspace-variables/staging_aks.tfvars.json
Labels: DevOps, deploy, deploy_v2
