Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2023-01, with the labels that each got.

#2997 [5063] Create report for performance profiles
  app/controllers/guidance_controller.rb
  app/controllers/reports_controller.rb
  app/controllers/trainees_controller.rb
  app/helpers/navigation_helper.rb
  app/models/academic_cycle.rb
  app/views/guidance/performance_profiles.html.erb
  app/views/guidance/show.html.erb
  app/views/layouts/application.html.erb
  app/views/reports/index.html.erb
  app/views/reports/itt_new_starter_data_sign_off.html.erb
  app/views/reports/performance_profiles.html.erb
  config/routes.rb
  config/settings.yml
  spec/controllers/guidance_controller_spec.rb
  spec/controllers/reports_controller_spec.rb
  spec/features/reports/viewing_performance_profiles_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/reports/index.rb
  spec/support/page_objects/reports/performance_profiles.rb
Labels: deploy

#3012 Use hidden span rather than class to fix NVDA bug
  app/views/funding/payment_schedules/_month_breakdown.html.erb
Labels: deploy

#3011 Add documentation of how to generate AR keys
  docs/ar_encryption_setup.md
Labels: documentation, DevOps

#2951 [5010] Improve uniqueness check on trainee id
  app/forms/training_details_form.rb
  app/services/find_empty_trainees.rb
  spec/forms/training_details_form_spec.rb
  spec/services/find_empty_trainees_spec.rb
Labels: deploy

#3013 [5081] Add autocomplete to lead school admin index page
  app/components/form_components/schools_autocomplete/script.js
  app/views/system_admin/lead_schools/index.html.erb
Labels: deploy

#3028 Added news entry about academic year filter
  db/service_updates.yml
Labels: deploy

#3032 potential fix of dead jobs QA error
  app/services/dead_jobs/base.rb
Labels: deploy

#3033 Remove course_award column that has been confusing users
  app/models/reports/trainee_report.rb
  app/models/reports/trainees_report.rb
  spec/models/reports/trainee_report_spec.rb
  spec/services/exports/export_trainees_service_spec.rb
  spec/services/exports/export_trainees_to_file_service_spec.rb
Labels: deploy

#3043 Clarify how HEIs should fix performance profile data
  app/controllers/guidance_controller.rb
  app/views/guidance/performance_profiles.html.erb
Labels: deploy

#3047 Temporarily remove course columns that are causing confusion
  app/models/reports/trainee_report.rb
  app/models/reports/trainees_report.rb
  spec/models/reports/trainee_report_spec.rb
  spec/services/exports/export_trainees_service_spec.rb
  spec/services/exports/export_trainees_to_file_service_spec.rb
Labels: deploy

#3051 [5166] Allow changes to withdrawal dates and reasons for system admins
  app/components/record_details/view.rb
  app/controllers/trainees/confirm_withdrawals_controller.rb
  app/forms/withdrawal_form.rb
  app/policies/trainee_policy.rb
  app/services/trainees/create_timeline_events.rb
  spec/features/trainee_actions/withdraw_trainee_spec.rb
  spec/forms/withdrawal_form_spec.rb
  spec/policies/trainee_policy_spec.rb
  spec/support/page_objects/trainees/record.rb
Labels: deploy

#3057 [5158] Fix trainees showing as missing degree subject for unknown or not applicable HESA codes
  Gemfile
  Gemfile.lock
  app/services/degrees/dfe_reference.rb
  db/data/20230123100908_fix_unmapped_trainee_degree_subjects.rb
  spec/services/degrees/create_from_hesa_spec.rb
  spec/services/degrees/dfe_reference_spec.rb
Labels: deploy

#3069 reset SNYK default app scan setting
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
Labels: DevOps

#3063 [5113] Allow system admin to edit ITT end date for HESA trainees
  app/forms/course_details_form.rb
  app/forms/itt_dates_form.rb
  app/helpers/dates_helper.rb
  app/views/trainees/course_details/edit.html.erb
  app/views/trainees/itt_dates/edit.html.erb
  spec/forms/course_details_form_spec.rb
Labels: deploy
