Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2023-07, with the labels that each got.

#3338 [5577] Amended the default course year as the academic year is going to change
  app/controllers/trainees/publish_course_details_controller.rb
  config/settings.yml
  lib/tasks/example_data.rake
  spec/factories/courses.rb
  spec/factories/trainees.rb
  spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
  spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
  spec/features/trainee_actions/change_course_spec.rb
Labels: DO NOT MERGE, deploy

#3363 Migrate qa to aks
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  config/settings/qa_aks.yml
  terraform/aks/.terraform.lock.hcl
  terraform/aks/provider.tf
  terraform/aks/statuscake.tf
  terraform/aks/workspace-variables/qa_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/register_qa.tfvars.json
Labels: DevOps

#3350 [5578] - Update view and LanguageSpecialismsForm for multiple selects
  app/controllers/trainees/apply_applications/course_details_controller.rb
  app/controllers/trainees/language_specialisms_controller.rb
  app/controllers/trainees/subject_specialisms_controller.rb
  app/forms/language_specialisms_form.rb
  app/forms/publish_course_details_form.rb
  app/helpers/course_details_helper.rb
  app/services/calculate_subject_specialism_type.rb
  app/views/trainees/language_specialisms/edit.html.erb
  config/locales/en.yml
  spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
  spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
  spec/forms/language_specialisms_form_spec.rb
  spec/support/page_objects/trainees/language_specialism.rb
Labels: deploy

#3386 Add sanitised data db restore for staging env
  .github/workflows/database-backup.yml
  .github/workflows/restore-staging-sanitised.yml
  config/settings/staging_aks.yml
Labels: DevOps

#3405 Disable analytics for staging aks
  config/settings/staging_aks.yml
Labels: DevOps

#3409 Remove compress flag from staging aks restore
  .github/workflows/database-backup.yml
  .github/workflows/restore-staging-sanitised.yml
Labels: DevOps

#3407 [5627] Change default course cycle for trainees registered after 1 July
  app/forms/course_years_form.rb
  app/services/trainees/set_academic_cycles.rb
  app/views/trainees/course_years/edit.html.erb
  spec/components/funding/view_spec.rb
  spec/factories/trainees.rb
  spec/features/trainee_actions/change_course_spec.rb
  spec/forms/course_years_form_spec.rb
  spec/services/trainees/set_academic_cycles_spec.rb
Labels: deploy_v2

#3415 [5668] Nip a few N+1s
  app/controllers/funding/base_funding_controller.rb
  app/controllers/system_admin/users_controller.rb
  app/models/bulk_update/recommendations_upload.rb
Labels: deploy_v2

#3419 [5625] - Update funding UI page for 2023/2024
  app/views/trainees/funding/bursaries/_grant_form.html.erb
  app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
  app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
  config/locales/en.yml
Labels: deploy_v2

#3418 Migrate productiondata env to aks
  .github/workflows/backup-and-restore.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-backup.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
Labels: DevOps

#3426 Fix secret in backup workflow
  .github/workflows/database-backup.yml
Labels: DevOps

#3431 [5680] Add banner to warn of downtime
  app/views/layouts/application.html.erb
  config/settings.yml
Labels: deploy_v2

#3436 Migrate production environment to AKS
  .github/actions/deploy_v2/action.yml
  .github/workflows/backup-and-restore.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/database-backup.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  config/settings/production_aks.yml
  terraform/aks/workspace-variables/production_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/register_production.tfvars.json
Labels: deploy_v2

#3451 Fix database backup disk space issue
  .github/workflows/database-backup.yml
Labels: DevOps

#3454 [5709] - update itt-outcome DQT endpoints with trainee slug
  app/services/dqt/recommend_for_award.rb
  app/services/dqt/trainee_update.rb
  app/services/dqt/withdraw_trainee.rb
  spec/services/dqt/recommend_for_award_spec.rb
  spec/services/dqt/update_spec.rb
  spec/services/dqt/withdraw_trainee_spec.rb
Labels: DO NOT MERGE

#3459 [xxxx] Switch to schema load for review app
  terraform/aks/workspace-variables/review_aks.tfvars.json
Labels: deploy_v2
