Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2023-06, with the labels that each got.

#3317 terraform aks db modules name using service_name
  terraform/aks/databases.tf
  terraform/aks/workspace-variables/production_aks_Terrafile
  terraform/aks/workspace-variables/productiondata_aks_Terrafile
  terraform/aks/workspace-variables/staging_aks_Terrafile
Labels: deploy_v2

#3314 [5525][BUG FIX] Fix form degrees validation mechanism
  app/forms/degrees_form.rb
  app/models/trainee.rb
  spec/forms/degrees_form_spec.rb
Labels: deploy

#3307 [5475] Handle impossible dates in bulk upload
  app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
  config/locales/en.yml
  config/webpacker.yml
  spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
Labels: deploy

#3328 Add AKS productiondata environment
  .github/actions/deploy_v2/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-v2.yml
  .github/workflows/scheduled-aks-db-restore.yml
  .gitignore
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/productiondata_aks.tfvars.json
Labels: DevOps

#3326 [5546] - Update training initiatives
  app/helpers/funding_helper.rb
  config/initializers/training_routes.rb
  config/locales/en.yml
  spec/models/trainee_spec.rb
Labels: deploy

#3332 fix syntax error in scheduled-aks-db-restore wf
  .github/workflows/scheduled-aks-db-restore.yml
Labels: DevOps

#3334 Update guidance about registering trainees through HESA
  app/views/guidance/registering_trainees_through_hesa.md
Labels: deploy

#3337 fix for aks module changes
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/provider.tf
  terraform/modules/azure/main.tf
Labels: deploy, deploy_v2

#3342 [4979] Add funding rules for 2023/24
  config/initializers/training_routes.rb
  db/data/20230619122848_add_funding_rules_for_20232024.rb
  db/seeds.rb
Labels: deploy

#3351 Change github token used for dependabot merge
  .github/workflows/build-and-deploy.yml
Labels: DevOps

#3312 Update content in missing data banner
  app/components/notice_banner/view.html.erb
  app/view_objects/missing_data_banner_view.rb
  config/locales/en.yml
  spec/view_objects/missing_data_banner_view_spec.rb
Labels: deploy

#3364 Bump pkgconf version to fix CVE-2023-24056
  Dockerfile
Labels: DevOps, security, deploy, deploy_v2

#3374 Disable hesa trn requests from prod aks env
  config/settings/production_aks.yml
Labels: DevOps

#3375 Fix delete review app to delete dependabot rv apps
  .github/workflows/delete-review-app.yml
Labels: DevOps

#3376 Update aks module provider versions
  terraform/aks/.terraform.lock.hcl
  terraform/aks/provider.tf
Labels: DevOps, deploy_v2
