Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2024-01, with the labels that each got.

#3899 [6532] Validate `Placement#postcode` and `urn`
  app/forms/placement_form.rb
  config/locales/en.yml
  spec/forms/placement_form_spec.rb
Labels: deploy_v2

#3904 Withdrawal Reason Character Limit
  app/forms/withdrawal/extra_information_form.rb
  config/locales/en.yml
  spec/features/trainee_actions/withdraw_trainee_spec.rb
Labels: deploy_v2

#3878 [6438] Refactor pending trns page to include trn response
  app/assets/stylesheets/components/_accordion.scss
  app/assets/stylesheets/components/_all.scss
  app/helpers/support/dqt_helper.rb
  app/models/dqt/trn_request.rb
  app/views/system_admin/pending_trns/index.html.erb
  config/locales/en.yml
  spec/features/system_admin/pending_trns/pending_trns_spec.rb
  spec/helpers/support/dqt_helper_spec.rb
  spec/models/dqt/trn_request_spec.rb
Labels: deploy_v2

#3898 [6413] Update bulk recommend content
  app/controllers/bulk_update/recommendations_base_controller.rb
  app/controllers/bulk_update/recommendations_uploads_controller.rb
  app/controllers/reports_controller.rb
  app/models/reports/bulk_recommend_empty_report.rb
  app/services/exports/bulk_recommend_empty_export.rb
  app/views/bulk_update/recommendations_uploads/_upload_trainees.html.erb
  app/views/bulk_update/recommendations_uploads/new.html.erb
  config/routes.rb
  spec/features/bulk_upload/recommending_trainees_spec.rb
  spec/services/exports/bulk_recommend_empty_export_spec.rb
  spec/support/recommendations_uploads_helper.rb
Labels: deploy_v2

#3913 Order of Placements Not Preserved on Updates
  app/jobs/bulk_update/placements/import_row_job.rb
  app/services/bulk_update/placements/import_rows.rb
  spec/jobs/bulk_update/placements/import_row_job_spec.rb
  spec/services/bulk_update/placements/import_rows_spec.rb
Labels: deploy_v2

#3901 cicd post migration code cleanup
  .github/actions/bring-docker-image-up/action.yml
  .github/actions/deploy/action.yml
  .github/actions/smoke-test/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/database-backup.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/next-academic-year-tests.yml
  .github/workflows/smoke-test.yml
  .github/workflows/tests.yml
  Makefile
  README.md
  docs/aks-cheatsheet.md
  docs/govuk_paas.md
  global_config/dv_review.sh
  global_config/production.sh
  global_config/productiondata.sh
  global_config/qa.sh
  global_config/review.sh
  global_config/staging.sh
  terraform/aks/application.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/dv_review.tfvars.json
  terraform/aks/workspace-variables/dv_review_Terrafile
  terraform/aks/workspace-variables/dv_review_backend.tfvars
  terraform/aks/workspace-variables/production.tfvars.json
  terraform/aks/workspace-variables/production_Terrafile
  terraform/aks/workspace-variables/production_backend.tfvars
  terraform/aks/workspace-variables/productiondata.tfvars.json
  terraform/aks/workspace-variables/productiondata_Terrafile
  terraform/aks/workspace-variables/productiondata_backend.tfvars
  terraform/aks/workspace-variables/qa.tfvars.json
  terraform/aks/workspace-variables/qa_Terrafile
  terraform/aks/workspace-variables/qa_backend.tfvars
  terraform/aks/workspace-variables/review.tfvars.json
  terraform/aks/workspace-variables/review_Terrafile
  terraform/aks/workspace-variables/review_backend.tfvars
  terraform/aks/workspace-variables/staging.tfvars.json
  terraform/aks/workspace-variables/staging_Terrafile
  terraform/aks/workspace-variables/staging_backend.tfvars
  terraform/modules/azure/data.tf
  terraform/modules/azure/main.tf
  terraform/modules/statuscake/main.tf
  terraform/modules/statuscake/provider.tf
  terraform/modules/statuscake/variables.tf
Labels: DevOps, deploy

#3914 [6579] Added static upload funding index page
  .rubocop.yml
  app/controllers/system_admin/upload_fundings_controller.rb
  app/helpers/users_helper.rb
  app/views/system_admin/_tab_nav.html.erb
  app/views/system_admin/upload_fundings/index.html.erb
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  spec/features/system_admin/upload_funding/viewing_upload_funding_spec.rb
  spec/helpers/users_helper_spec.rb
  spec/support/features/common_steps.rb
Labels: deploy

#3930 [6580] Implement funding upload flow (without saving)
  app/controllers/system_admin/funding_uploads/confirmations_controller.rb
  app/controllers/system_admin/funding_uploads_controller.rb
  app/controllers/system_admin/upload_fundings_controller.rb
  app/forms/system_admin/funding_upload_form.rb
  app/helpers/support/funding_uploads_helper.rb
  app/helpers/users_helper.rb
  app/models/system_admin/funding_upload.rb
  app/views/system_admin/_tab_nav.html.erb
  app/views/system_admin/funding_uploads/confirmations/show.html.erb
  app/views/system_admin/funding_uploads/index.html.erb
  app/views/system_admin/funding_uploads/new.html.erb
  config/analytics_blocklist.yml
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/productiondata.yml
  config/settings/qa.yml
  config/settings/review.yml
  config/settings/staging.yml
  config/settings/test.yml
  db/migrate/20240111072604_create_funding_uploads.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/features/system_admin/funding_uploads/creating_a_funding_upload_spec.rb
  spec/features/system_admin/funding_uploads/viewing_funding_uploads_spec.rb
  spec/features/system_admin/upload_funding/viewing_upload_funding_spec.rb
  spec/forms/system_admin/funding_upload_form_spec.rb
  spec/helpers/users_helper_spec.rb
Labels: deploy

#3948 [6551] Content updates for performance profile guidance
  app/views/guidance/manage_placements.html.erb
  app/views/guidance/performance_profiles.html.erb
Labels: deploy

#3923 [6571] Add javascript fallback to autocompletes in register
  app/components/select_placement_school/view.html.erb
  app/components/select_placement_school/view.rb
  app/controllers/trainees/placement_school_searches_controller.rb
  app/controllers/trainees/placements_controller.rb
  app/forms/placement_form.rb
  app/forms/placements_form.rb
  app/forms/select_placement_school_form.rb
  app/models/placement.rb
  app/services/school_search.rb
  app/views/trainees/placement_school_searches/_search.html.erb
  app/views/trainees/placement_school_searches/edit.html.erb
  app/views/trainees/placement_school_searches/new.html.erb
  app/views/trainees/placements/_form.html.erb
  app/views/trainees/placements/search.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/select_placement_school/view_spec.rb
  spec/features/form_sections/teacher_training_data/placements/adding_trainee_placements_spec.rb
  spec/features/form_sections/teacher_training_data/placements/editing_trainee_placements_spec.rb
  spec/forms/placement_form_spec.rb
  spec/forms/select_placement_school_form_spec.rb
Labels: deploy

#3954 [6528] - Add logins to the smoke tests
  config/settings.yml
  spec/smoke/login_spec.rb
  spec/spec_helper_smoke.rb
Labels: deploy

#3953 [6621] Added skip to results for the filter
  app/views/trainees/_search_results.html.erb
Labels: deploy

#3950 Rake file and service to import placements from CSV
  app/services/placements/import_from_csv.rb
  lib/tasks/import_hesa_placements.rake
  spec/factories/uploads.rb
  spec/fixtures/files/placements_import.csv
  spec/services/placements/import_from_csv_spec.rb
Labels: deploy

#3940 [6618] Send welcome email after user creation not first login
  app/controllers/sessions_controller.rb
  app/controllers/system_admin/users_controller.rb
  app/services/send_welcome_email_service.rb
  spec/controllers/sessions_controller_spec.rb
  spec/features/system_admin/users/creating_a_new_user_spec.rb
  spec/services/send_welcome_email_service_spec.rb
Labels: deploy

#3939 [6622] Clear funding when reinstatement happens
  app/forms/reinstatement_form.rb
  spec/forms/reinstatement_form_spec.rb
Labels: deploy

#3942 [5735] Update govuk frontend
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_autocomplete.scss
  app/assets/stylesheets/components/_start_page_banner.scss
  app/assets/stylesheets/components/_status_card.scss
  app/assets/stylesheets/components/_tab_navigation.scss
  app/assets/stylesheets/filter_toggle_button.scss
  app/assets/stylesheets/govuk_style_setup.scss
  app/components/admin_feature/view.html.erb
  app/components/header/view.html.erb
  app/components/status_tag/view.html.erb
  app/components/status_tag/view.rb
  app/javascript/scripts/components/form_components/autocomplete/script.js
  app/javascript/scripts/components/form_components/country_autocomplete.js
  app/javascript/scripts/components/form_components/providers_autocomplete.js
  app/javascript/scripts/components/form_components/schools_autocomplete.js
  app/javascript/scripts/components/form_components/users_autocomplete.js
  app/views/layouts/application.html.erb
  config/initializers/assets.rb
  config/locales/en.yml
  package.json
  service_unavailable_page/web/public/internal/index.html
  spec/components/application_record_card/view_spec.rb
  spec/components/status_tag/view_spec.rb
  spec/features/form_sections/personal_and_education_details/reviewing_apply_trainee_data_spec.rb
  spec/features/trainee_actions/edit_trainee_record_spec.rb
  spec/support/page_objects/trainees/review_draft.rb
  spec/support/shared_examples/rendering_the_funding_section.rb
  yarn.lock
Labels: deploy

#3969 [6647] Return funding uploads on index page
  app/controllers/system_admin/funding_uploads_controller.rb
  app/helpers/support/funding_uploads_helper.rb
  app/models/system_admin/funding_upload.rb
  app/views/system_admin/funding_uploads/index.html.erb
  spec/features/system_admin/funding_uploads/creating_a_funding_upload_spec.rb
  spec/models/system_admin/funding_upload_spec.rb
Labels: deploy

#3971 [6681] Add new placement regression - uses non-JS flow
  app/controllers/trainees/placements_controller.rb
  app/forms/placement_form.rb
Labels: deploy

#3979 [6618] Move welcome email trigger to lead school controller
  app/controllers/system_admin/user_lead_schools_controller.rb
  app/controllers/system_admin/users_controller.rb
  spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
  spec/features/system_admin/users/creating_a_new_user_spec.rb
Labels: deploy

#3982 [6667] Set up info endpoint with feature flag, versioning and token authentication
  app/controllers/api/base_controller.rb
  app/controllers/api/info_controller.rb
  app/lib/route_constraints/register_api_constraint.rb
  app/lib/route_constraints/system_admin_constraint.rb
  app/lib/system_admin_constraint.rb
  config/routes/api_routes.rb
  config/routes/system_admin_routes.rb
  config/settings.yml
  config/settings/production.yml
  config/settings/productiondata.yml
  spec/lib/route_constraints/system_admin_constraint_spec.rb
  spec/lib/system_admin_constraint_spec.rb
  spec/requests/api/v0.1/info_spec.rb
Labels: deploy, API

#3983 [6667] Move legacy `/api` routes to `/autocomplete`
  app/controllers/autocomplete/application_controller.rb
  app/controllers/autocomplete/providers_controller.rb
  app/controllers/autocomplete/schools_controller.rb
  app/controllers/autocomplete/users_controller.rb
  app/javascript/scripts/components/form_components/providers_autocomplete.js
  app/javascript/scripts/components/form_components/schools_autocomplete.js
  app/javascript/scripts/components/form_components/users_autocomplete.js
  config/routes.rb
  config/routes/api_routes.rb
  config/routes/autocomplete_routes.rb
  spec/controllers/autocomplete/providers_controller_spec.rb
  spec/controllers/autocomplete/schools_controller_spec.rb
Labels: deploy

#3974 [925] Enable Azure RBAC authentication on AKS #2
  .github/actions/deploy/action.yml
  .github/workflows/database-backup.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .tool-versions
  Makefile
  docs/aks-cheatsheet.md
  terraform/aks/provider.tf
Labels: deploy

#3991 Privacy notice text changes to include Jisc
  app/views/pages/privacy_notice.md
Labels: deploy

#3992 Update bulk placements page to say that up to 5 placements can be added
  app/views/bulk_update/placements/new.html.erb
Labels: deploy

#3994 [937] Add missing kubelogin to DB backup workflow
  .github/workflows/database-backup.yml
Labels: DevOps

#3985 [6668] initial api documentation set up framework to read content
  app/controllers/api/guide_controller.rb
  app/views/api/guide/show.md
  app/views/layouts/api/guide.html.erb
  config/routes/api_routes.rb
  spec/requests/api/v0.1/guide_spec.rb
Labels: API

#3986 [6620] Add new page updating expected end date when trainees are reinstated
  app/components/reinstatement_details/view.html.erb
  app/components/reinstatement_details/view.rb
  app/controllers/trainees/confirm_reinstatements_controller.rb
  app/controllers/trainees/reinstatements/update_end_dates_controller.rb
  app/controllers/trainees/reinstatements_controller.rb
  app/forms/itt_end_date_form.rb
  app/services/form_store.rb
  app/views/trainees/confirm_reinstatements/show.html.erb
  app/views/trainees/reinstatements/show.html.erb
  app/views/trainees/reinstatements/update_end_dates/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/reinstatement_details/view_preview.rb
  spec/components/reinstatement_details/view_spec.rb
  spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
  spec/features/trainee_actions/reinstating_a_trainee_spec.rb
  spec/forms/itt_end_date_form_spec.rb
Labels: deploy
