Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2024-08, with the labels that each got.

#4532 Remove type column from lead_partners#index
  app/views/system_admin/lead_partners/index.html.erb
Labels: deploy

#4527 Feature - Change Remaining References to Lead School
  app/components/trainee_personal_details/view.html.erb
  app/controllers/autocomplete/schools_controller.rb
  app/controllers/autocomplete/users_controller.rb
  app/controllers/organisations_controller.rb
  app/controllers/personas_controller.rb
  app/controllers/system_admin/funding/payment_schedules_controller.rb
  app/controllers/system_admin/funding/trainee_summaries_controller.rb
  app/controllers/system_admin/funding_controller.rb
  app/controllers/system_admin/funding_uploads_controller.rb
  app/forms/schools/lead_school_form.rb
  app/helpers/funding_helper.rb
  app/helpers/school_helper.rb
  app/helpers/users_helper.rb
  app/lib/funding/parsers/lead_partner_payment_schedules.rb
  app/lib/funding/parsers/lead_partner_trainee_summaries.rb
  app/models/system_admin/funding_upload.rb
  app/services/funding/lead_partner_payment_schedules_importer.rb
  app/services/funding/lead_partner_trainee_summaries_importer.rb
  app/services/funding_data_importer.rb
  app/services/school_search.rb
  app/services/send_welcome_email_service.rb
  app/view_objects/funding/trainee_summary_view.rb
  app/views/funding/payment_schedules/show.html.erb
  app/views/funding/trainee_summaries/_bursaries.html.erb
  app/views/funding/trainee_summaries/_scholarships.html.erb
  app/views/funding/trainee_summaries/show.html.erb
  app/views/guidance/_schools.html.erb
  app/views/system_admin/funding_uploads/index.html.erb
  config/locales/en.yml
  lib/tasks/funding.rake
  spec/components/trainee_personal_details/view_spec.rb
  spec/controllers/autocomplete/schools_controller_spec.rb
  spec/factories/system_admin/funding_upload.rb
  spec/features/system_admin/funding_uploads/viewing_funding_uploads_spec.rb
  spec/forms/schools/lead_school_form_spec.rb
  spec/helpers/users_helper_spec.rb
  spec/lib/funding/parsers/lead_partner_payment_schedules_spec.rb
  spec/lib/funding/parsers/lead_partner_trainee_summaries_spec.rb
  spec/models/system_admin/funding_upload_spec.rb
  spec/services/funding/lead_partner_payment_schedules_importer_spec.rb
  spec/services/funding/lead_partner_trainee_summaries_importer_spec.rb
  spec/services/funding_data_importer_spec.rb
  spec/services/school_search_spec.rb
  spec/support/fixtures/invalid_lead_partner_payment_schedules.csv
  spec/support/fixtures/invalid_lead_partner_trainee_summaries.csv
  spec/support/fixtures/lead_partner_payment_schedules.csv
  spec/support/fixtures/lead_partner_trainee_summaries.csv
  spec/view_objects/funding/trainee_summary_view_spec.rb
Labels: DO NOT MERGE, deploy, refactor

#4549 [7460] - use slug in error reporting
  .tool-versions
  app/lib/notify_on_timeout.rb
  app/services/dqt/trainee_update.rb
  package.json
Labels: deploy

#4553 [xxxx] Amended to alpine 3.20 and ruby 3.2.5 and nodejs 20.15.1
  .devcontainer/Dockerfile
  .github/actions/smoke-test/action.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  package.json
Labels: deploy

#4543 [7457] Refactor github actions to smaller units
  .github/actions/build/action.yml
  .github/actions/deploy/action.yml
  .github/actions/lint/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/smoke-test/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/database-backup.yml
  .github/workflows/next-academic-year-tests.yml
  .github/workflows/reset-sandbox-database.yml
  .github/workflows/tests.yml
Labels: deploy

#4564 [7450] Add support tooling for support to mark a school as a lead partner
  app/components/system_admin/schools/details/view.html.erb
  app/components/system_admin/schools/details/view.rb
  app/controllers/system_admin/lead_partners_controller.rb
  app/controllers/system_admin/schools/confirm_details_controller.rb
  app/controllers/system_admin/schools_controller.rb
  app/forms/system_admin/school_form.rb
  app/models/lead_partner.rb
  app/models/school.rb
  app/services/concerns/cacheable.rb
  app/services/form_store.rb
  app/services/form_stores/system_admin/school_form_store.rb
  app/services/lead_partner_search.rb
  app/views/system_admin/schools/confirm_details/show.html.erb
  app/views/system_admin/schools/edit.html.erb
  app/views/system_admin/schools/index.html.erb
  app/views/system_admin/schools/show.html.erb
  app/views/system_admin/user_lead_partners/_no_results.html.erb
  config/analytics.yml
  config/locales/en.yml
  config/routes/system_admin_routes.rb
  db/migrate/20240809135932_add_discarded_at_to_lead_partners.rb
  db/migrate/20240814110540_add_foreign_keys_uniqueness_indices_to_lead_partners.rb
  db/schema.rb
  spec/factories/lead_partners.rb
  spec/features/form_sections/teacher_training_data/non_js_lead_partner_search_spec.rb
  spec/features/system_admin/lead_partners/add_user_to_lead_partner_spec.rb
  spec/features/system_admin/schools/edit_school_spec.rb
  spec/forms/system_admin/school_form_spec.rb
  spec/models/school_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/lead_partners/index.rb
  spec/support/page_objects/system_admin/schools/confirm_details.rb
  spec/support/page_objects/system_admin/schools/edit.rb
  spec/support/page_objects/system_admin/schools/show.rb
Labels: deploy

#4573 [7498] Amended dfe-analytics to v1.14.1
  Gemfile
  Gemfile.lock
Labels: deploy

#4551 Migrating Lead School to Lead Partner - Part III
  app/models/bulk_update/recommendations_upload_row.rb
  app/models/concerns/lead_school_migratable.rb
  app/models/funding/trainee_summary_row.rb
  app/models/hesa/student.rb
  app/models/lead_school_user.rb
  app/models/school.rb
  app/models/user.rb
  app/services/copy_lead_school_to_lead_partner_service.rb
  app/services/lead_school_user_import.rb
  app/views/guidance/_schools.html.erb
  config/analytics.yml
  config/analytics_blocklist.yml
  db/data/20240812145432_migrate_lead_school_to_lead_parter_for_recommendation_uploads.rb
  db/data/20240813122725_migrate_lead_school_to_lead_partner_for_funding_trainee_summary_rows.rb
  db/data/20240813131129_migrate_lead_school_to_lead_partner_for_hesa_students.rb
  db/migrate/20240812144711_add_lead_partner_to_bulk_update_recommendations_upload_rows.rb
  db/migrate/20240813122304_add_lead_parnter_urn_to_funding_trainee_summary_rows.rb
  db/migrate/20240813130940_add_lead_partner_urn_to_hesa_students.rb
  db/migrate/20240815130820_drop_lead_school_users.rb
  db/schema.rb
  docs/database-diagram.jpg
  lib/tasks/copy_lead_school_to_lead_partner.rake
  lib/tasks/lead_school_user_import.rake
  spec/factories/users.rb
  spec/features/organisation_contexts_spec.rb
  spec/models/bulk_update/recommendations_upload_row_spec.rb
  spec/models/concerns/lead_school_migratable_spec.rb
  spec/models/funding/trainee_summary_row_spec.rb
  spec/models/lead_school_user_spec.rb
  spec/models/school_spec.rb
  spec/models/users_spec.rb
  spec/services/copy_lead_school_to_lead_partner_service_spec.rb
  spec/services/lead_school_user_import_spec.rb
  spec/support/features/authentication_steps.rb
Labels: deploy

#4591 [7528] Add LeadPartner#funding_trainee_summaries
  app/models/lead_partner.rb
  spec/factories/users.rb
  spec/features/funding/payment_schedule_spec.rb
  spec/features/funding/trainee_summary_spec.rb
  spec/models/lead_partner_spec.rb
Labels: deploy

#4601 Add service maintenance page
  .github/workflows/disable-maintenance.yml
  .github/workflows/enable-maintenance.yml
  Makefile
  maintenance_page/Dockerfile
  maintenance_page/html/assets/fonts/bold-affa96571d-v2-b092ddd6.woff
  maintenance_page/html/assets/fonts/bold-b542beb274-v2-616e5f21.woff2
  maintenance_page/html/assets/fonts/light-94a07e06a1-v2-bb962e0c.woff2
  maintenance_page/html/assets/fonts/light-f591b13f7d-v2-f03d82c2.woff
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.br
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.gz
  maintenance_page/html/assets/images/favicon-ec189703.svg
  maintenance_page/html/assets/images/favicon-ec189703.svg.br
  maintenance_page/html/assets/images/favicon-ec189703.svg.gz
  maintenance_page/html/assets/images/govuk-crest-2x.png
  maintenance_page/html/assets/images/govuk-crest.png
  maintenance_page/html/assets/images/govuk-icon-180-e0835e78.png
  maintenance_page/html/assets/images/govuk-icon-192-7b8e00f8.png
  maintenance_page/html/assets/images/govuk-icon-512-587f7e53.png
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.br
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.gz
  maintenance_page/html/assets/images/govuk-opengraph-image-bd4c811b.png
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.gz
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.gz
  maintenance_page/html/assets/images/icon-toggle-plus-minus-257426a1.svg
  maintenance_page/html/index.html
  maintenance_page/html/javascript/govuk-frontend-5.3.1.min.js
  maintenance_page/html/stylesheets/govuk-frontend-5.3.1.min.css
  maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
  maintenance_page/manifests/maintenance/service_maintenance.yml
  maintenance_page/manifests/production/ingress_external_to_main.yml
  maintenance_page/manifests/production/ingress_external_to_main2.yml
  maintenance_page/manifests/production/ingress_external_to_maintenance.yml
  maintenance_page/manifests/production/ingress_external_to_maintenance2.yml
  maintenance_page/manifests/production/ingress_internal_to_main.yml
  maintenance_page/manifests/production/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/production/ingress_maintenance.yml
  maintenance_page/manifests/production/ingress_temp_to_main.yml
  maintenance_page/manifests/qa/ingress_external_to_main.yml
  maintenance_page/manifests/qa/ingress_external_to_main2.yml
  maintenance_page/manifests/qa/ingress_external_to_maintenance.yml
  maintenance_page/manifests/qa/ingress_external_to_maintenance2.yml
  maintenance_page/manifests/qa/ingress_internal_to_main.yml
  maintenance_page/manifests/qa/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/qa/ingress_maintenance.yml
  maintenance_page/manifests/qa/ingress_temp_to_main.yml
  maintenance_page/nginx.conf
  maintenance_page/scripts/failback.sh
  maintenance_page/scripts/failover.sh
Labels: DevOps

#4599 Upgrade prod postgres sku to GP_Standard_D4ds_v5
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/production.tfvars.json
Labels: DevOps

#4577 Lead School to Lead Partner Part IV
  app/components/system_admin/schools/details/view.rb
  app/forms/system_admin/school_form.rb
  app/lib/hesa/parsers/itt_record.rb
  app/models/school.rb
  app/services/api/v0_1/hesa_mapper/attributes.rb
  app/services/trainees/create_from_csv_row.rb
  app/services/trainees/create_from_hesa.rb
  app/views/system_admin/schools/index.html.erb
  config/analytics.yml
  db/migrate/20240822150430_drop_lead_school_from_schools.rb
  db/schema.rb
  docs/database-diagram.jpg
  lib/tasks/example_data.rake
  lib/tasks/schools_data.rake
  spec/components/school_details/view_preview.rb
  spec/factories/schools.rb
  spec/factories/trainees.rb
  spec/features/system_admin/funding_uploads/creating_a_funding_upload_spec.rb
  spec/forms/placement_form_spec.rb
  spec/forms/system_admin/school_form_spec.rb
  spec/lib/hesa/parsers/itt_record_spec.rb
  spec/lib/tasks/schools_data_get_lead_schools_from_publish_spec.rb
  spec/lib/tasks/schools_data_update_lead_schools_from_publish_spec.rb
  spec/models/trainee_spec.rb
  spec/policies/user_policy_spec.rb
  spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
  spec/services/exports/funding_trainee_summary_data_spec.rb
  spec/services/funding/lead_partner_payment_schedules_importer_spec.rb
  spec/services/funding/lead_partner_trainee_summaries_importer_spec.rb
  spec/services/send_welcome_email_service_spec.rb
  spec/services/trainees/create_from_csv_row_spec.rb
  spec/services/trainees/create_from_hesa_spec.rb
Labels: deploy

#4605 Change Lead School to Lead Partner for Trainee Reports
  app/models/reports/bulk_recommend_report.rb
  app/models/reports/trainee_report.rb
  app/models/reports/trainees_report.rb
  app/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows.rb
  app/services/bulk_update/recommendations_uploads/trainee_lookup.rb
  app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
  app/services/exports/report_csv_enumerator_service.rb
  config/locales/en.yml
  spec/models/reports/trainee_report_spec.rb
  spec/services/exports/bulk_recommend_export_spec.rb
  spec/services/exports/export_trainees_service_spec.rb
  spec/services/exports/export_trainees_to_file_service_spec.rb
Labels: deploy
