Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2024-03, with the labels that each got.

#4059 Register API - Monitoring Initial Solution
  Gemfile
  Gemfile.lock
  app/controllers/api/base_controller.rb
  config/initializers/yabeda.rb
  config/routes/system_admin_routes.rb
  spec/support/shared_examples/register_api_endpoint.rb
Labels: deploy

#4111 Update statuscake contact group and monitor path
  terraform/aks/workspace-variables/production.tfvars.json
  terraform/aks/workspace-variables/qa.tfvars.json
  terraform/aks/workspace-variables/staging.tfvars.json
Labels: DevOps

#4103 [6830] Prevent duplicate placements from being created
  Gemfile.lock
  app/models/placement.rb
  app/services/api/trainees/save_placement_response.rb
  db/migrate/20240305115708_add_unique_constraints_to_placements.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/models/placement_spec.rb
  spec/services/api/trainees/save_placement_response_spec.rb
Labels: API

#4129 [6863] Api Set up providers in sandbox for vendor testing
  .github/workflows/reset-sandbox-database.yml
  lib/tasks/vendor.rake
  spec/lib/tasks/vendor_create_spec.rb
  spec/lib/tasks/vendor_swap_spec.rb
Labels: deploy

#4133 [6846] Update API documentation
  app/assets/stylesheets/api-docs.scss
  app/assets/stylesheets/application.scss
  app/views/api_docs/pages/help.md
  app/views/api_docs/pages/home.md
  app/views/api_docs/pages/reference.md
  app/views/api_docs/pages/release-notes.md
  app/views/api_docs/pages/release_notes.md
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0/_reference.md
  app/views/layouts/application.html.erb
  spec/features/api_docs/reference_spec.rb
Labels: deploy
