Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2024-07, with the labels that each got.

#4434 Deadline dates updated for 2024-25
  app/views/guidance/dates_and_deadlines.html.erb
Labels: deploy

#4448 Refactor Withdraw Endpoint
  app/views/api_docs/reference/v1.0/_reference.md
  public/openapi/v1.0.yaml
  spec/requests/api/v1_0/trainees/post_withdraw_spec.rb
Labels: deploy

#4452 [7323] Fix bulk award uploads
  app/models/reports/trainee_report.rb
  app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
Labels: deploy

#4443 [7308] Prevent QTS recommendation being made in Register UI if degree information has not been added.
  app/components/trainee_about/view.html.erb
  app/components/trainee_about/view.rb
  app/controllers/concerns/missing_fields_checkable.rb
  app/controllers/trainees/base_controller.rb
  app/controllers/trainees_controller.rb
  app/forms/degrees_form.rb
  app/forms/submissions/missing_data_validator.rb
  app/views/trainees/show.html.erb
  config/locales/en.yml
  spec/components/trainee_about/view_spec.rb
  spec/factories/trainees.rb
  spec/features/trainee_actions/recording_training_outcome_spec.rb
  spec/forms/submissions/missing_data_validator_spec.rb
Labels: bug, deploy

#4387 [7229] Amended the course program type mapping for 2023-2024 and 2024-2025
  app/controllers/system_admin/duplicate_apply_applications_controller.rb
  app/services/teacher_training_api/import_course.rb
  config/initializers/training_routes.rb
  config/settings/test.yml
  spec/features/trainee_actions/change_course_spec.rb
  spec/features/trainee_actions/edit_trainee_training_route_spec.rb
  spec/services/teacher_training_api/import_course_spec.rb
  spec/support/api_stubs/recruits_api.rb
Labels: deploy

#4446 Prevent QTS recommendation being made in Bulk Recommend if degree information has not been added.
  app/forms/submissions/missing_data_validator.rb
  app/services/bulk_update/recommendations_uploads/trainee_lookup.rb
  app/services/bulk_update/recommendations_uploads/validate_trainee.rb
  app/views/trainees/show.html.erb
  spec/factories/trainees.rb
  spec/features/bulk_upload/recommending_trainees_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/bulk_update/recommendations_uploads/confirmation.rb
  spec/support/page_objects/bulk_update/recommendations_uploads/show.rb
Labels: deploy

#4457 Update productiondata.yml
  config/settings/productiondata.yml
Labels: deploy

#4456 [7333] Revise the What type of training are they doing? page for 2024-2025 academic year
  app/views/trainees/training_routes/_form_fields.html.erb
  config/locales/en.yml
  spec/features/end_to_end/provider_led_postgrad_salaried_journey_spec.rb
  spec/features/trainee_actions/creating_a_new_trainee_spec.rb
Labels: deploy

#4469 Removed academic year from link text
  app/views/guidance/show.html.erb
  app/views/landing_page/home.html.erb
Labels: deploy

#4460 Metrics Endpoint for API Monitoring
  app/controllers/api/base_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/api_monitorable.rb
  app/controllers/concerns/basic_authenticable.rb
  config/initializers/yabeda.rb
  config/routes.rb
  config/routes/system_admin_routes.rb
  docs/api-monitoring.md
  spec/requests/api/monitoring_spec.rb
  spec/requests/authentication_spec.rb
Labels: deploy

#4474 News article added
  db/service_updates.yml
Labels: ready for review, deploy

#4475 Scrape custom metrics
  config/environments/production.rb
  terraform/aks/application.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/production.tfvars.json
  terraform/aks/workspace-variables/qa.tfvars.json
  terraform/aks/workspace-variables/sandbox.tfvars.json
  terraform/aks/workspace-variables/staging.tfvars.json
Labels: DevOps, deploy

#4444 [1830, 7253] Update Register for 2024/25 funding rules
  config/initializers/mappings/allocation_subject_to_specialism_mapping.rb
  config/initializers/subjects/allocation_subjects.rb
  config/initializers/training_routes.rb
  db/data/20240703223532_add_funding_rules_for_2024_25.rb
  db/seeds.rb
Labels: deploy

#4485 [7354] Implement ITT reform on Register API - part 1
  app/components/school_details/view.rb
  app/components/schools/view.rb
  app/forms/schools/lead_school_form.rb
  app/models/api/v0_1/trainee_attributes.rb
  app/models/reports/trainee_report.rb
  app/models/trainee.rb
  app/serializers/api/v0_1/trainee_serializer.rb
  app/services/api/get_trainees_service.rb
  app/services/api/v0_1/hesa_mapper/attributes.rb
  app/services/trainees/create_from_hesa.rb
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0-pre/_reference.md
  app/views/trainees/lead_schools/_results.html.erb
  app/views/trainees/lead_schools/edit.html.erb
  config/analytics.yml
  db/migrate/20240719095753_rename_lead_school_not_applicable_to_lead_partner_not_applicable.rb
  db/schema.rb
  spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
  spec/factories/trainees.rb
  spec/features/form_sections/teacher_training_data/edit_schools_spec.rb
  spec/models/reports/trainee_report_spec.rb
  spec/models/trainee_spec.rb
  spec/requests/api/v0_1/post_hesa_trainees_spec.rb
  spec/requests/api/v0_1/put_trainee_spec.rb
  spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
  spec/requests/api/v1_0_pre/put_trainee_spec.rb
  spec/serializers/api/v0_1/trainee_serializer_spec.rb
  spec/services/trainees/create_from_hesa_spec.rb
  spec/support/page_objects/trainees/edit_lead_school.rb
  spec/support/shared_examples/school_form_validations.rb
Labels: deploy

#4501 [7400] Added variant of itt reform training route naming
  app/components/route_indicator/view.rb
  app/views/trainees/funding/bursaries/_grant_form.html.erb
  app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
  config/locales/en.yml
  spec/components/route_indicator/view_spec.rb
  spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
Labels: deploy

#4504 Content changes for 24 25 academic year
  app/views/guidance/_census_sign_off_inside.html.erb
  app/views/guidance/_census_sign_off_outside.html.erb
  app/views/guidance/_course_details.html.erb
  app/views/guidance/_database_only.html.erb
  app/views/guidance/_funding.html.erb
  app/views/guidance/_personal_details.html.erb
  app/views/guidance/_schools.html.erb
  app/views/guidance/_trainee_progress.html.erb
  app/views/guidance/about_register_trainee_teachers.md
  app/views/guidance/census_sign_off.md
  app/views/guidance/check_data.md
  app/views/guidance/hesa_register_data_mapping.html.erb
  app/views/guidance/manage_placements.html.erb
  app/views/guidance/performance_profiles_outside.html.erb
  app/views/guidance/registering_trainees_through_hesa.md
  app/views/reports/_outside_period.html.erb
  app/views/request_an_account/index.html.erb
Labels: DO NOT MERGE, WIP, deploy

#4512 [7413] Remove “Lead Schools” from Choose organisation page
  app/components/personas/view.rb
  app/controllers/organisations_controller.rb
  app/controllers/system_admin/lead_partners_controller.rb
  app/controllers/system_admin/user_lead_partners_controller.rb
  app/forms/system_admin/user_lead_schools_form.rb
  app/lib/user_with_organisation_context.rb
  app/policies/trainee_policy.rb
  app/views/organisations/index.html.erb
  app/views/system_admin/_tab_nav.html.erb
  config/initializers/personas.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/productiondata.yml
  config/settings/qa.yml
  config/settings/review.yml
  lib/tasks/example_data.rake
  spec/components/personas/view_spec.rb
  spec/features/organisation_contexts_spec.rb
  spec/features/system_admin/lead_partners/add_user_to_lead_partner_spec.rb
  spec/features/system_admin/lead_partners/list_lead_partners_spec.rb
  spec/features/trainee_actions/viewing_an_existing_trainee_spec.rb
  spec/policies/trainee_policy_spec.rb
Labels: deploy

#4516 Further content changes
  app/views/guidance/bulk_recommend_trainees.md
  app/views/guidance/registering_trainees_through_hesa.md
  config/locales/en.yml
Labels: deploy

#4445 [7229] Amended recruitment cycle year and default course year to `2024`
  config/settings.yml
  spec/factories/trainees.rb
  spec/features/trainee_actions/recording_training_outcome_spec.rb
Labels: DO NOT MERGE

#4480 Update Recruitment Cycle Years For 24/25
  config/settings.yml
  spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
  spec/factories/trainees.rb
  spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
Labels: DO NOT MERGE

#4478 [7177] Optionally add lead partner
  spec/factories/trainees.rb
Labels: DO NOT MERGE, deploy
