Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2024-11, with the labels that each got.

#4780 [7765] Update file encoding error message to new content
  config/locales/en.yml
  spec/features/bulk_upload/recommending_trainees_spec.rb
  spec/services/bulk_update/recommendations_uploads/validate_file_spec.rb
Labels: deploy

#4782 [7754] Amended the privacy notice
  app/views/pages/privacy_notice.md
  spec/features/pages_spec.rb
Labels: deploy

#4777 [7770] Upgrade to ruby 3.3
  .devcontainer/Dockerfile
  .github/actions/smoke-test/action.yml
  .rubocop.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: deploy

#4790 [7772] - remove scss_lint-govuk
  .scss-lint.yml
  Gemfile
  Gemfile.lock
Labels: deploy

#4809 [7813] Fix example_data.rake
  lib/tasks/example_data.rake
  spec/factories/providers.rb
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
Labels: bug, deploy

#4767 [7744] Create upload summary page part 2
  app/controllers/bulk_update/trainees/submissions_controller.rb
  app/controllers/bulk_update/trainees/uploads_controller.rb
  app/forms/bulk_update/bulk_add_trainees_submit_form.rb
  app/forms/bulk_update/bulk_add_trainees_upload_form.rb
  app/models/bulk_update/row_error.rb
  app/models/bulk_update/trainee_upload.rb
  app/models/bulk_update/trainee_upload_row.rb
  app/policies/bulk_update/submissions/trainee_upload_policy.rb
  app/policies/bulk_update/trainee_upload_policy.rb
  app/services/bulk_update/add_trainees/import_rows.rb
  app/services/bulk_update/add_trainees/validate_file.rb
  app/services/bulk_update/recommendations_uploads/validate_trainee.rb
  app/views/bulk_update/bulk_updates/index.html.erb
  app/views/bulk_update/trainees/uploads/new.html.erb
  app/views/bulk_update/trainees/uploads/show.html.erb
  config/analytics.yml
  config/locales/en.yml
  db/migrate/20241101133718_add_error_type_to_bulk_update_row_error.rb
  db/migrate/20241114153414_add_index_errored_on_id_errored_on_type_to_bulk_update_errors.rb
  db/schema.rb
  spec/factories/bulk_update/trainee_upload_rows.rb
  spec/factories/bulk_update/trainee_uploads.rb
  spec/factories/users.rb
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
  spec/models/bulk_update/row_error_spec.rb
  spec/models/bulk_update/trainee_upload_row_spec.rb
  spec/models/bulk_update/trainee_upload_spec.rb
  spec/policies/bulk_update/submissions/trainee_upload_policy_spec.rb
  spec/policies/bulk_update/trainee_upload_policy_spec.rb
  spec/services/bulk_update/add_trainees/import_rows_spec.rb
Labels: deploy

#4818 [7674] Check and update API docs - part 1
  app/controllers/api/trainees/degrees_controller.rb
  app/controllers/api/trainees/placements_controller.rb
  app/views/api_docs/reference/v1.0-pre/_reference.md
  config/routes/api_routes.rb
  config/settings.yml
  public/openapi/v0.1.yaml
  public/openapi/v1.0-pre.yaml
  spec/features/api_docs/home_spec.rb
  spec/features/api_docs/reference_spec.rb
  spec/requests/api/v0_1/audit_trail_attribution_spec.rb
  spec/requests/api/v0_1/duplicate_trainees_spec.rb
  spec/requests/api/v0_1/get_trainee_spec.rb
  spec/requests/api/v0_1/get_trainees_spec.rb
  spec/requests/api/v0_1/post_hesa_trainees_spec.rb
  spec/requests/api/v0_1/put_trainee_spec.rb
  spec/requests/api/v0_1/trainees/delete_placement_spec.rb
  spec/requests/api/v0_1/trainees/get_degree_spec.rb
  spec/requests/api/v0_1/trainees/get_degrees_spec.rb
  spec/requests/api/v0_1/trainees/get_placement_spec.rb
  spec/requests/api/v0_1/trainees/get_placements_spec.rb
  spec/requests/api/v0_1/trainees/post_deferral_spec.rb
  spec/requests/api/v0_1/trainees/post_recommend_for_qts_spec.rb
  spec/requests/api/v0_1/trainees/post_withdraw_spec.rb
  spec/requests/api/v0_1/trainees/put_placement_spec.rb
  spec/requests/api/v1_0_pre/audit_trail_attribution_spec.rb
  spec/requests/api/v1_0_pre/duplicate_trainees_spec.rb
  spec/requests/api/v1_0_pre/get_trainee_spec.rb
  spec/requests/api/v1_0_pre/get_trainees_spec.rb
  spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
  spec/requests/api/v1_0_pre/put_trainee_spec.rb
  spec/requests/api/v1_0_pre/trainees/delete_placement_spec.rb
  spec/requests/api/v1_0_pre/trainees/get_degree_spec.rb
  spec/requests/api/v1_0_pre/trainees/get_degrees_spec.rb
  spec/requests/api/v1_0_pre/trainees/get_placement_spec.rb
  spec/requests/api/v1_0_pre/trainees/get_placements_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_deferral_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_recommend_for_qts_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_withdraw_spec.rb
  spec/requests/api/v1_0_pre/trainees/put_placement_spec.rb
  spec/support/openapi.rb
  spec/support/shared_examples/register_api_endpoint.rb
  spec/support/shared_examples/register_versioned_api_get_request.rb
Labels: deploy

#4821 [7833] Install turbo-rails
  Gemfile
  Gemfile.lock
  app/javascript/application.js
  app/javascript/scripts/components/form_components/lead_partners_autocomplete.js
  app/views/layouts/application.html.erb
  app/views/trainees/employing_schools/details/edit.html.erb
  app/views/trainees/lead_partners/details/edit.html.erb
  config/initializers/content_security_policy.rb
  package.json
  yarn.lock
Labels: deploy

#4811 [7785] - Create confirmation email and trigger sending
  app/controllers/bulk_update/trainees/submissions_controller.rb
  app/mailers/csv_submitted_for_processing_email_mailer.rb
  app/services/send_csv_submitted_for_processing_email_service.rb
  config/environments/test.rb
  config/settings.yml
  config/settings/test.yml
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
  spec/mailers/csv_submitted_for_processing_email_mailer_spec.rb
  spec/services/send_csv_submitted_for_processing_email_service_spec.rb
Labels: deploy

#4800 [7797] Allow a CSV bulk upload to be cancelled through the Summary page
  app/assets/stylesheets/application.scss
  app/controllers/bulk_update/trainees/submissions_controller.rb
  app/controllers/bulk_update/trainees/uploads_controller.rb
  app/models/bulk_update/trainee_upload.rb
  app/policies/bulk_update/trainee_upload_policy.rb
  app/views/bulk_update/trainees/uploads/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/factories/bulk_update/trainee_uploads.rb
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
  spec/models/bulk_update/trainee_upload_spec.rb
  spec/policies/bulk_update/submissions/trainee_upload_policy_spec.rb
  spec/policies/bulk_update/trainee_upload_policy_spec.rb
Labels: deploy

#4842 Use storage account for all backups
  .github/workflows/database-backup.yml
  .github/workflows/reset-sandbox-database.yml
  docs/setup-development.md
Labels: DevOps
