Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2024-02, with the labels that each got.

#3966 [6628] Fix placements CSV export placements in wrong order
  app/models/placement.rb
  app/models/reports/trainee_report.rb
  app/services/placements_imported_from_hesa.rb
  spec/models/reports/trainee_report_spec.rb
  spec/services/placements_imported_from_hesa_spec.rb
Labels: deploy

#3999 [937] Fix environment name in DB backup job
  .github/workflows/database-backup.yml
Labels: DevOps

#3980 [6671] Basic Rack attack setup for API
  Gemfile
  Gemfile.lock
  config/initializers/rack_attack.rb
  config/settings.yml
Labels: API

#3997 Register API: GET Trainee
  app/controllers/api/base_controller.rb
  app/controllers/api/trainees_controller.rb
  app/serializers/trainee_serializer.rb
  config/routes/api_routes.rb
  spec/requests/api/v0.1/info_spec.rb
  spec/requests/api/v0.1/trainees_spec.rb
  spec/support/shared_examples/register_api_endpoint.rb
Labels: API

#4000 [6670] Set up config for sandbox environment
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
  .rubocop.yml
  Makefile
  README.md
  config/environments/sandbox.rb
  config/settings/sandbox.yml
  db/migrate/20210118132920_regenerate_slugs_on_trainees.rb
  db/migrate/20220324162356_update_bursary_tiers_enum_values.rb
  docs/aks-cheatsheet.md
  docs/aks_modules.md
  global_config/sandbox.sh
  terraform/aks/workspace-variables/app_config.yml
  terraform/aks/workspace-variables/sandbox.tfvars.json
  terraform/aks/workspace-variables/sandbox_Terrafile
  terraform/aks/workspace-variables/sandbox_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/register_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/register_sandbox_backend.tfvars
Labels: DevOps, deploy, API

#4017 [6678] Fix complete? column in export
  app/models/reports/trainee_report.rb
  app/models/reports/trainees_report.rb
  spec/models/reports/trainee_report_spec.rb
Labels: deploy

#4002 [6669] Initial Register API documentation
  app/components/navigation_bar/view.html.erb
  app/components/navigation_bar/view.rb
  app/controllers/api_docs/base_controller.rb
  app/controllers/api_docs/pages_controller.rb
  app/controllers/api_docs/reference_controller.rb
  app/views/api_docs/pages/home.md
  app/views/api_docs/pages/reference.md
  app/views/api_docs/pages/release_notes.md
  app/views/api_docs/reference/show.html.erb
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0/_reference.md
  app/views/layouts/_markdown_page.html.erb
  app/views/layouts/api_docs/pages.html.erb
  app/views/layouts/application.html.erb
  config/routes/api_routes.rb
  spec/features/api_docs/home_spec.rb
  spec/features/api_docs/reference_spec.rb
Labels: deploy, API

#4020 POST Trainee - Register API
  app/controllers/api/trainees_controller.rb
  app/models/api/degree_attributes.rb
  app/models/api/placement_attributes.rb
  app/models/api/trainee_attributes.rb
  app/models/trainee.rb
  app/serializers/trainee_serializer.rb
  config/routes/api_routes.rb
  spec/models/api/degree_attributes_spec.rb
  spec/models/api/placement_attributes_spec.rb
  spec/models/api/trainee_attributes_spec.rb
  spec/requests/api/v0.1/trainees_spec.rb
Labels: API

#4035 [6771] Amended `itt_started_but_trainee_did_not_start` message
  config/locales/en.yml
Labels: deploy

#4057 Content changes to placement guidance
  app/views/bulk_update/bulk_updates/index.html.erb
  app/views/bulk_update/placements/new.html.erb
  app/views/guidance/manage_placements.html.erb
  app/views/guidance/performance_profiles_outside.html.erb
Labels: deploy

#4066 Bump sidekiq from 6.5.8 to 6.5.12
  Gemfile.lock
Labels: dependencies, ruby

#4075 [6680] Fix funding nav item
  app/helpers/navigation_helper.rb
Labels: deploy

#4081 [6679] - show nav menu toggle only when js is enabled
  app/components/header/view.html.erb
Labels: deploy

#4082 [6792] Register api allow providers to create update and delete placements
  app/controllers/api/trainees/placements_controller.rb
  app/controllers/api/trainees_controller.rb
  app/models/api/attributes.rb
  app/models/api/placement_attributes.rb
  app/models/api/placement_attributes/v01.rb
  app/models/api/trainee_attributes/v01.rb
  app/serializers/placement_serializer/v01.rb
  app/serializers/serializer.rb
  app/services/api/trainees/save_placement_response.rb
  config/routes/api_routes.rb
  spec/models/api/placement_attributes/v01_spec.rb
  spec/requests/api/v0.1/trainees/delete_placement_spec.rb
  spec/requests/api/v0.1/trainees/get_placement_spec.rb
  spec/requests/api/v0.1/trainees/get_placements_spec.rb
  spec/requests/api/v0.1/trainees/post_placement_spec.rb
  spec/requests/api/v0.1/trainees/put_placement_spec.rb
  spec/requests/api/v0.1/trainees/withdraw_spec.rb
  spec/services/api/trainees/save_placement_response_spec.rb
  spec/support/request_helpers.rb
Labels: deploy
