Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2024-05, with the labels that each got.

#4256 [7057] Use “api” as the Record Source if Applicable
  app/models/trainee.rb
  config/locales/en.yml
  spec/factories/trainees.rb
  spec/models/trainee_spec.rb
Labels: deploy

#4291 [7109] Incomplete data returned by POST trainee (B)
  app/models/api/hesa_trainee_detail_attributes/v01.rb
  app/models/api/trainee_attributes/v01.rb
  app/services/api/map_hesa_attributes/v01.rb
  config/analytics_blocklist.yml
  db/migrate/20240515134857_rename_hesa_trainee_details_postgrad_apprenticeship_start_date.rb
  db/schema.rb
  spec/factories/hesa/trainee_details.rb
  spec/models/api/trainee_attributes/v01_spec.rb
  spec/requests/api/v0.1/post_hesa_trainees_spec.rb
  spec/requests/api/v0.1/put_trainee_spec.rb
  spec/serializers/trainee_serializer/v01_spec.rb
Labels: bug, deploy

#4317 send test container logs to logit.io
  terraform/aks/application.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/qa.tfvars.json
  terraform/aks/workspace-variables/review.tfvars.json
  terraform/aks/workspace-variables/staging.tfvars.json
Labels: DevOps, deploy

#4318 Update github actions to latest versions
  .github/actions/bring-docker-image-up/action.yml
  .github/actions/deploy/action.yml
Labels: DevOps, deploy

#4319 send prod container logs to logit.io
  terraform/aks/workspace-variables/production.tfvars.json
  terraform/aks/workspace-variables/productiondata.tfvars.json
  terraform/aks/workspace-variables/sandbox.tfvars.json
Labels: DevOps

#4315 [7172] Added max length for field lengths summary
  app/forms/personal_details_form.rb
  app/views/api_docs/reference/v0.1/_reference.md
  config/locales/en.yml
  public/api-docs/reference/Register_API_Reference_v0.1.xlsx
  spec/forms/personal_details_form_spec.rb
  spec/requests/api/v0.1/put_trainee_spec.rb
Labels: deploy
