Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2025-02, with the labels that each got.

#5028 [8125] Change postgrad and undergrad on training routes page
  config/locales/en.yml
  spec/view_objects/funding/trainee_summary_view_spec.rb
Labels: deploy

#5018 [8119] Support up to 3 placements in the CSV
  app/services/bulk_update/add_trainees/import_row.rb
  app/services/bulk_update/add_trainees/import_rows.rb
  app/views/bulk_update/add_trainees/reference_docs/fields.yaml
  public/csv/bulk_create_trainee.csv
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
  spec/fixtures/files/bulk_update/trainee_uploads/empty_file_with_headers.csv
  spec/fixtures/files/bulk_update/trainee_uploads/failed_with_two_errors.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees_with_degree.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees_with_placement.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees_with_two_errors.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees_with_unparseable_date.csv
  spec/services/bulk_update/add_trainees/import_row_spec.rb
Labels: deploy

#5040 [8162] Enable lead partners for early_years_undergrad
  config/initializers/training_routes.rb
  config/locales/en.yml
  spec/features/end_to_end/early_years_undergrad_journey_spec.rb
  spec/support/features/course_details_steps.rb
  spec/support/features/training_route_steps.rb
Labels: deploy

#5050 [7974] Amended to show message for no bulk trainee upload
  app/views/bulk_update/add_trainees/uploads/index.html.erb
Labels: deploy

#5030 [8129] Added content for `Duplication Validations`
  app/views/api_docs/reference/v1.0-pre/_reference.md
  spec/requests/api/v0_1/trainees/post_placement_spec.rb
  spec/requests/api/v0_1/trainees/put_placement_spec.rb
Labels: deploy

#5064 Create separate storage account for sanitised bkp
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace-variables/production.tfvars.json
  terraform/modules/azure/storage.tf
  terraform/modules/azure/variables.tf
Labels: DevOps

#5055 [8199] - Fix dynamic heading on reasons page
  app/forms/withdrawal/reason_form.rb
  app/views/trainees/withdrawal/reasons/edit.html.erb
  config/locales/en.yml
Labels: deploy

#5077 Remove az logout from backup workflow
  .github/workflows/database-backup.yml
Labels: DevOps

#5071 Use oidc for github workflows
  .github/actions/bring-docker-image-up/action.yml
  .github/actions/build/action.yml
  .github/actions/coverage-tests/action.yml
  .github/actions/deploy/action.yml
  .github/actions/lint/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/code-coverage.yml
  .github/workflows/database-backup.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/disable-maintenance.yml
  .github/workflows/enable-maintenance.yml
  .github/workflows/next-academic-year-tests.yml
  .github/workflows/reset-sandbox-database.yml
  .github/workflows/tests.yml
  Makefile
  terraform/aks/provider.tf
Labels: DevOps, deploy

#5082 Fix permissions on next-academic-year-tests gh wf
  .github/workflows/next-academic-year-tests.yml
Labels: DevOps

#5079 Stop using azure kv for review app sentry dsn
  .github/actions/bring-docker-image-up/action.yml
  .github/actions/coverage-tests/action.yml
  .github/actions/lint/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/code-coverage.yml
  .github/workflows/tests.yml
Labels: DevOps, deploy

#5043 [7983] Change apostrophes from straight to curly style
  app/assets/stylesheets/components/_navigation_bar.scss
  app/components/bulk_update/trainee_uploads/show/in_progress/view.html.erb
  app/components/bulk_update/trainee_uploads/show/succeeded/view.html.erb
  app/components/cancel_link/view.rb
  app/lib/api/error_response.rb
  app/lib/code_sets/degree_types.rb
  app/models/trainee.rb
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0-pre/_reference.md
  app/views/bulk_update/add_trainees/reference_docs/fields.yaml
  app/views/bulk_update/add_trainees/uploads/new.html.erb
  app/views/guidance/_census_sign_off_inside.html.erb
  app/views/guidance/_census_sign_off_outside.html.erb
  app/views/guidance/bulk_upload_placement_data.html.erb
  app/views/guidance/census_sign_off.md
  app/views/guidance/check_data.md
  app/views/guidance/manage_placements.html.erb
  app/views/guidance/performance_profiles.html.erb
  app/views/guidance/registering_trainees_through_hesa.md
  app/views/reports/itt_new_starter_data_sign_off.html.erb
  app/views/reports/performance_profiles/new.html.erb
  app/views/trainees/placements/details/edit.html.erb
  config/locales/cookies/cookie_policy/en.yml
  config/locales/en.yml
  docs/adr/0001-record-architecture-decisions.md
  docs/adr/0002-use-adr-tools-with-custom-template.md
  docs/adr/0003-connections-to-dttp-dynamics.md
  docs/adr/0004-non-integer-trainee-ids.md
  docs/adr/0006-academic-cycles.md
  docs/adr/0007-store-academic-cycles-on-trainees.md
  docs/adr/0008-enable-course-year-picker.md
  docs/adr/0009-enable-sidekiq-worker-on-productiondata.md
  docs/adr/template.md
  docs/aks_modules.md
  docs/api-monitoring.md
  docs/api.md
  docs/big_query_setup.md
  docs/healthcheck_and_ping_endpoints.md
  docs/logging.md
  docs/machine-setup.md
  docs/openapi.md
  docs/setup-development.md
  docs/support_playbook.md
  docs/uploading_funding_csvs.md
  lib/tasks/import_hesa_placements.rake
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
  spec/features/trainee_actions/add_lead_partner_and_employing_school_spec.rb
  spec/features/trainee_actions/withdraw_trainee_spec.rb
  spec/services/api/trainees/withdraw_response_spec.rb
Labels: deploy
