Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2025-09, with the labels that each got.

#5562 [8809] Launch Send Trainee Data Direct
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-backup.yml
  .github/workflows/deploy.yml
  config/settings.yml
  config/settings/csv-sandbox.yml
  config/settings/development.yml
  config/settings/pen.yml
  config/settings/production.yml
  config/settings/qa.yml
  config/settings/review.yml
  config/settings/sandbox.yml
  config/settings/staging.yml
Labels: DO NOT MERGE

#5605 [8860] Reconfigure production workers to optimise for STDD - part 3
  terraform/aks/application.tf
Labels: deploy

#5614 [8890] Missing TRN requests for trainees created via CSV bulk add trainees
  app/services/api/create_trainee.rb
  app/services/bulk_update/add_trainees/import_row.rb
  app/services/bulk_update/add_trainees/import_rows.rb
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
  spec/services/bulk_update/add_trainees/import_rows_spec.rb
Labels: deploy

#5641 [8908][8907][8911] Bullet points, change tense, remove valid on API docs
  spec/support/page_objects/base.rb
  tech_docs/source/api-docs/index.html.md.erb
  tech_docs/source/partials/reference_data/_attribute.html.md.erb
Labels: deploy

#5591 [8838] Remove unneeded example text
  app/lib/hesa/code_sets/training_initiatives.rb
  app/views/bulk_update/add_trainees/reference_docs/fields.yaml
  config/locales/reference_data/training_initiative.yml
  data/hesa/training_initiatives.csv
  tech_docs/source/reference-data/v2025.0/training-initiative.html.md
Labels: DO NOT MERGE, deploy

#5655 Bump rack from 2.2.17 to 2.2.18
  Gemfile.lock
  tech_docs/Gemfile.lock
Labels: deploy
