Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2025-03, with the labels that each got.

#5090 Add staging to maintenance page
  .github/workflows/maintenance.yml
  maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
  maintenance_page/manifests/staging/ingress_external_to_main.yml
  maintenance_page/manifests/staging/ingress_external_to_main2.yml
  maintenance_page/manifests/staging/ingress_external_to_maintenance.yml
  maintenance_page/manifests/staging/ingress_external_to_maintenance2.yml
  maintenance_page/manifests/staging/ingress_internal_to_main.yml
  maintenance_page/manifests/staging/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/staging/ingress_maintenance.yml
  maintenance_page/manifests/staging/ingress_temp_to_main.yml
Labels: DevOps

#5088 Use build-docker-image github action
  .github/actions/bring-docker-image-up/action.yml
  .github/actions/build/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/code-coverage.yml
  .github/workflows/next-academic-year-tests.yml
  .github/workflows/tests.yml
Labels: DevOps, deploy

#5084 [8198] Create Organisation page
  app/controllers/organisation_settings_controller.rb
  app/helpers/application_helper.rb
  app/lib/user_with_organisation_context.rb
  app/policies/organisation_settings_policy.rb
  app/views/organisation_settings/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/organisation_settings_spec.rb
  spec/policies/organisation_settings_policy_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/organisation_settings.rb
Labels: deploy

#5065 [8171] Return correct error messages for missing data and invalid data
  app/models/api/v0_1/degree_attributes.rb
  app/models/api/v0_1/hesa_trainee_detail_attributes.rb
  app/models/api/v0_1/trainee_attributes.rb
  app/services/api/v0_1/hesa_mapper/attributes.rb
  app/services/api/v0_1/hesa_mapper/degree_attributes.rb
  app/services/concerns/has_course_attributes.rb
  config/initializers/constants/hesa_mapper_constants.rb
  config/locales/en.yml
  public/openapi/v0.1.yaml
  public/openapi/v1.0-pre.yaml
  spec/fixtures/files/bulk_update/trainee_uploads/failed_with_two_errors.csv
  spec/models/api/v0_1/degree_attributes_spec.rb
  spec/models/api/v0_1/hesa_trainee_detail_attributes_spec.rb
  spec/models/api/v0_1/trainee_attributes_spec.rb
  spec/requests/api/v0_1/post_hesa_trainees_spec.rb
  spec/requests/api/v0_1/put_trainee_spec.rb
  spec/requests/api/v0_1/trainees/post_degrees_spec.rb
  spec/requests/api/v0_1/trainees/put_degrees_spec.rb
  spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
  spec/requests/api/v1_0_pre/put_trainee_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_degrees_spec.rb
  spec/requests/api/v1_0_pre/trainees/put_degrees_spec.rb
Labels: deploy

#5107 Add namespace to postgres restore
  .github/workflows/postgres-restore.yml
Labels: DevOps

#5069 [8197] - Upgrade to ruby 3.4.2
  .devcontainer/Dockerfile
  .github/actions/smoke-test/action.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  spec/requests/api/rack_attack_spec.rb
  spec/support/shared_examples/dead_jobs.rb
Labels: deploy

#5112 [8253] Fixed static dfe sign in redirect uri
  app/controllers/sign_out_controller.rb
  app/models/dfe_sign_in_user.rb
  config/initializers/omniauth.rb
  spec/controllers/sign_out_controller_spec.rb
  spec/models/dfe_sign_in_user_spec.rb
Labels: deploy

#5058 [8041] - Update withdrawals api endpoint
  app/controllers/api/trainees/withdraw_controller.rb
  app/forms/withdrawal/reason_form.rb
  app/models/api/v0_1/withdrawal_attributes.rb
  app/models/reports/trainee_report.rb
  app/models/trainee.rb
  app/serializers/api/v0_1/trainee_serializer.rb
  app/services/api/trainees/withdraw_response.rb
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0-pre/_reference.md
  config/locales/en.yml
  config/routes/api_routes.rb
  public/openapi/v0.1.yaml
  public/openapi/v1.0-pre.yaml
  spec/features/trainee_actions/withdraw_trainee_spec.rb
  spec/models/api/v0_1/withdrawal_attributes_spec.rb
  spec/requests/api/v0_1/trainees/post_withdraw_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_withdraw_spec.rb
  spec/serializers/api/v0_1/trainee_serializer_spec.rb
  spec/services/api/trainees/withdraw_response_spec.rb
Labels: deploy

#5087 [8219] Allow multiple placements at the same school
  app/components/placements/view.html.erb
  app/forms/placement_form.rb
  app/models/placement.rb
  app/models/trainee_withdrawal.rb
  app/services/api/trainees/save_placement_response.rb
  app/services/bulk_update/placements/import_row.rb
  app/services/bulk_update/placements/import_rows.rb
  app/services/bulk_update/placements/row.rb
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0-pre/_reference.md
  config/initializers/training_routes.rb
  config/locales/en.yml
  db/migrate/20250226164325_remove_urn_unique_contraint_from_placements.rb
  db/migrate/20250227152625_remove_address_and_postcode_unique_constraint_from_placements.rb
  db/migrate/20250304121701_change_trainee_id_column_null_in_trainee_withdrawals.rb
  db/migrate/20250305123050_remove_unique_index_in_bulk_update_placement_rows.rb
  db/schema.rb
  spec/components/status_tag/view_spec.rb
  spec/factories/bulk_update/placement_rows.rb
  spec/factories/trainees.rb
  spec/features/form_sections/teacher_training_data/placements/adding_trainee_placements_spec.rb
  spec/fixtures/files/bulk_update/placements/complete.csv
  spec/forms/placement_form_spec.rb
  spec/models/placement_spec.rb
  spec/requests/api/v0_1/trainees/post_placement_spec.rb
  spec/requests/api/v0_1/trainees/put_placement_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_placement_spec.rb
  spec/requests/api/v1_0_pre/trainees/put_placement_spec.rb
  spec/services/api/trainees/save_placement_response_spec.rb
  spec/services/bulk_update/placements/create_placement_rows_spec.rb
  spec/services/bulk_update/placements/import_rows_spec.rb
Labels: deploy

#5144 [8272] Create new self-serve token management index page
  app/components/authentication_tokens/details/view.html.erb
  app/components/authentication_tokens/details/view.rb
  app/controllers/authentication_tokens_controller.rb
  app/models/authentication_token.rb
  app/policies/authentication_token_policy.rb
  app/views/authentication_tokens/index.html.erb
  app/views/organisation_settings/show.html.erb
  config/analytics_blocklist.yml
  config/routes.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  db/migrate/20250314141354_add_attributes_to_authetication_tokens.rb
  db/migrate/20250318153401_add_status_to_authentication_tokens.rb
  db/schema.rb
  lib/tasks/example_data.rake
  spec/components/personas/view_spec.rb
  spec/factories/authentication_tokens.rb
  spec/factories/provider_users.rb
  spec/factories/providers.rb
  spec/features/organisation_settings_spec.rb
  spec/models/authentication_token_spec.rb
  spec/policies/authentication_token_policy_spec.rb
  spec/support/features/page_helpers.rb
  spec/support/page_objects/organisation_settings.rb
  spec/support/page_objects/tokens/index.rb
Labels: deploy

#5116 [8221] Send qualtrics survey to trainees after withdrawal or QTS award
  app/jobs/dqt/recommend_for_award_job.rb
  app/jobs/survey/send_job.rb
  app/lib/qualtrics_api/client.rb
  app/services/survey/award.rb
  app/services/survey/base.rb
  app/services/survey/withdraw.rb
  app/services/trainees/withdraw.rb
  config/settings.yml
  config/settings/production.yml
  config/settings/review.yml
  docs/qualtrics-old-dashboard.png
  docs/qualtrics.md
  spec/jobs/dqt/recommend_for_award_job_spec.rb
  spec/jobs/survey/send_job_spec.rb
  spec/services/survey/award_spec.rb
  spec/services/survey/base_spec.rb
  spec/services/survey/withdraw_spec.rb
  spec/services/trainees/withdraw_spec.rb
  spec/support/shared_examples/survey_service_examples.rb
Labels: deploy

#5156 [8272] Create new self-serve token management index page - part 2
  app/components/authentication_tokens/details/view.rb
  app/controllers/authentication_tokens_controller.rb
  app/models/authentication_token.rb
  app/policies/authentication_token_policy.rb
  app/views/organisation_settings/show.html.erb
  db/migrate/20250314141354_add_attributes_to_authetication_tokens.rb
  db/migrate/20250321143706_add_status_last_used_at_index_to_authentication_tokens.rb
  db/schema.rb
  lib/tasks/example_data.rake
  spec/factories/authentication_tokens.rb
  spec/features/organisation_settings_spec.rb
  spec/policies/authentication_token_policy_spec.rb
Labels: deploy

#5158 [8297] Add a Cron job to expire Authentication tokens
  app/jobs/authentication_tokens/expire_tokens_job.rb
  app/models/authentication_token.rb
  config/sidekiq_cron_schedule.yml
  db/migrate/20250324100449_add_expires_at_index_to_authentication_tokens.rb
  db/schema.rb
  spec/jobs/authentication_tokens/expire_tokens_job_spec.rb
  spec/models/authentication_token_spec.rb
Labels: deploy

#5153 [8188] / [8181] - Update CSV docs for bulk_update/add_trainees / CSV Guidance clarify that we don't need COURSEID or CTITLE
  app/views/bulk_update/add_trainees/reference_docs/fields.yaml
  app/views/csv_docs/pages/add_trainees.html.erb
Labels: deploy

#5165 [8294] Remove some internal Register fields from API responses
  app/serializers/api/v0_1/trainee_serializer.rb
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0-pre/_reference.md
  spec/requests/api/v0_1/post_hesa_trainees_spec.rb
  spec/requests/api/v0_1/put_trainee_spec.rb
  spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
  spec/requests/api/v1_0_pre/put_trainee_spec.rb
  spec/serializers/api/v0_1/trainee_serializer_spec.rb
Labels: deploy

#5170 [8310] Add deferral reason to API endpoint POST /trainees/{trainee_id}/defer
  app/controllers/api/trainees/deferrals_controller.rb
  app/models/authentication_token.rb
  app/models/trainee.rb
  app/services/api/trainees/deferral_service.rb
  app/views/api_docs/reference/v0.1/_reference.md
  app/views/api_docs/reference/v1.0-pre/_reference.md
  config/analytics.yml
  db/migrate/20250326142810_add_defer_reason_to_trainees.rb
  db/schema.rb
  public/openapi/v0.1.yaml
  public/openapi/v1.0-pre.yaml
  spec/requests/api/v0_1/trainees/post_deferral_spec.rb
  spec/requests/api/v0_1/trainees/post_placement_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_placement_spec.rb
  spec/serializers/api/v0_1/trainee_serializer_spec.rb
  spec/services/api/trainees/deferral_service_spec.rb
Labels: deploy
