Repository DFE-Digital/register-trainee-teachers, pull requests merged in 2025-05, with the labels that each got.

#5209 [8372] - Add 274 missing institutions for previous degrees
  Gemfile
  Gemfile.lock
  spec/requests/api/v0_1/trainees/post_degrees_spec.rb
  spec/requests/api/v1_0_pre/trainees/post_degrees_spec.rb
  spec/services/degrees/create_from_hesa_spec.rb
Labels: deploy

#5249 [8448] Added March edition to news
  db/service_updates.yml
Labels: deploy

#5245 [8459] Removed March 2025 Notification of changes
  app/views/csv_docs/pages/add_trainees.html.erb
Labels: deploy

#5240 Send api_request events to BigQuery
  Gemfile
  Gemfile.lock
  app/controllers/api/base_controller.rb
  spec/requests/dfe_analytics_api_request_events_spec.rb
Labels: deploy

#5253 [8469] Prepare for proposed changes to DfE Reference Data gem from TRA
  app/helpers/degrees_helper.rb
  app/lib/dqt/params/trn_request.rb
  spec/helpers/degrees_helper_spec.rb
Labels: DO NOT MERGE

#5251 [8461] Amended CSV docs contents fixes
  app/views/bulk_update/add_trainees/reference_docs/fields.yaml
Labels: deploy

#5252 [8458] Amended degree subject content updates
  app/views/api_docs/reference/v1.0-pre/_reference.md
  app/views/bulk_update/add_trainees/reference_docs/fields.yaml
Labels: deploy

#5266 [8506] undefined method 'provider' for nil
  app/controllers/api/base_controller.rb
Labels: deploy

#5250 [8414] Added April edition to news
  db/service_updates.yml
Labels: deploy

#5261 [8463] - SPIKE Determine how best to update complex error messages for API and CSV bulk add new trainees
  app/models/api/error_attribute_adapter.rb
  app/models/api/v1_0_pre/trainee_attributes.rb
  config/locales/en.yml
  spec/fixtures/files/bulk_update/trainee_uploads/failed_with_two_failed.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees_with_two_failed.csv
  spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
  spec/requests/api/v1_0_pre/put_trainee_spec.rb
Labels: deploy

#5274 [8508] Update phase and notification banners for CSV sandbox
  app/components/csv_sandbox_banner/view.html.erb
  app/components/csv_sandbox_banner/view.rb
  app/views/layouts/application.html.erb
  spec/components/csv_sandbox_banner/view_spec.rb
  spec/features/csv_sandbox_banner_spec.rb
Labels: deploy

#5281 Use delete review app github action
  .github/workflows/delete-review-app.yml
  Makefile
Labels: DevOps, deploy

#5271 Accessibility statement updated
  app/views/pages/accessibility.md
Labels: deploy

#5269 [8499] Clear disabilities if values change in a HESA/API update
  app/models/api/v0_1/trainee_attributes.rb
  app/models/api/v2025_0_rc/trainee_attributes.rb
  app/services/api/v0_1/update_trainee_service.rb
  app/services/trainees/create_from_hesa.rb
  spec/requests/api/v0_1/put_trainee_spec.rb
  spec/requests/api/v2025_0_rc/put_trainee_spec.rb
  spec/services/trainees/create_from_hesa_spec.rb
Labels: deploy

#5300 Fix delete-review-app for dependencies
  .github/workflows/delete-review-app.yml
Labels: DevOps

#5304 [8514] Update complex error messages used by both CSV and API
  app/models/api/v0_1/hesa_trainee_detail_attributes.rb
  app/models/api/v0_1/trainee_attributes.rb
  app/models/api/v2025_0_rc/degree_attributes.rb
  app/models/concerns/training_route_manageable.rb
  app/models/trainee.rb
  app/services/bulk_update/add_trainees/import_row.rb
  app/services/bulk_update/add_trainees/import_rows.rb
  app/views/bulk_update/add_trainees/reference_docs/fields.yaml
  config/locales/en.yml
  spec/factories/bulk_update/trainee_uploads.rb
  spec/features/bulk_upload/bulk_add_trainees_spec.rb
  spec/fixtures/files/bulk_update/trainee_uploads/failed_with_failed.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees_with_degree.csv
  spec/fixtures/files/bulk_update/trainee_uploads/five_trainees_with_failed.csv
  spec/models/api/v0_1/hesa_trainee_detail_attributes_spec.rb
  spec/models/api/v0_1/trainee_attributes_spec.rb
  spec/models/api/v2025_0_rc/degree_attributes_spec.rb
  spec/requests/api/v2025_0_rc/post_hesa_trainees_spec.rb
  spec/requests/api/v2025_0_rc/put_trainee_spec.rb
  spec/requests/api/v2025_0_rc/trainees/post_degrees_spec.rb
  spec/requests/api/v2025_0_rc/trainees/put_degrees_spec.rb
  spec/services/bulk_update/add_trainees/import_row_spec.rb
Labels: deploy

#5308 [8515] Update complex error messages used by API only
  app/models/api/v0_1/withdrawal_attributes.rb
  app/models/api/v2025_0_rc/withdrawal_attributes.rb
  app/services/api/trainees/award_recommendation_service.rb
  app/services/api/trainees/deferral_service.rb
  app/validators/api/trainees/award_recommendation_validator.rb
  app/validators/api/trainees/deferral_validator.rb
  config/locales/en.yml
  spec/requests/api/v0_1/trainees/post_deferral_spec.rb
  spec/requests/api/v0_1/trainees/post_recommend_for_qts_spec.rb
  spec/requests/api/v2025_0_rc/trainees/post_deferral_spec.rb
  spec/requests/api/v2025_0_rc/trainees/post_recommend_for_qts_spec.rb
  spec/requests/api/v2025_0_rc/trainees/post_withdraw_spec.rb
  spec/services/api/trainees/award_recommendation_service_spec.rb
  spec/services/api/trainees/deferral_service_spec.rb
  spec/services/api/trainees/withdraw_response_spec.rb
Labels: deploy
